#!/usr/bin/env node
/**
 * yaPDP media manifest drift test.
 *
 * Verifies that the committed media/manifest.json (generated by
 * tools/gen-media-manifest.js) still matches the images actually present in
 * media/: recomputes the expected logical-url list straight from the
 * directory and compares. If someone adds or removes an image without
 * regenerating the manifest, this test fails — the quick-boot wizard and
 * the Info page would otherwise advertise a stale image set.
 *
 * Also asserts the full repo ships every disk/tape image the quick-boot
 * wizard lists, so the wizard's default (unfiltered) view is honest.
 *
 * Run with:  node tests/media-manifest.test.js
 *
 * Exit code 0 = all tests passed, non-zero = failure.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");
const assert = require("assert");

const ROOT = path.join(__dirname, "..");
const MEDIA = path.join(ROOT, "media");
const MANIFEST = path.join(MEDIA, "manifest.json");

// Mirror of the naming rules in tools/gen-media-manifest.js — if the
// generator's rules change, update both sides together.
const EXCLUDE = new Set(["bootcode.ptap", "bootcode.ptap.zst"]);
const IMAGE_RE = /\.(dsk|tap|ptap)(\.zst)?$/;

function logicalUrl(file) {
    return file.endsWith(".zst") ? file.slice(0, -4) : file;
}

function expectedMediaList() {
    return fs.readdirSync(MEDIA)
        .filter((f) => IMAGE_RE.test(f) && !EXCLUDE.has(f) && !f.startsWith("."))
        .map(logicalUrl)
        .sort();
}

// Load the production osboot.js in an isolated VM context (same as the
// other module tests) to read BOOT_SCENARIOS.
function loadOSBoot() {
    const sandbox = { console };
    sandbox.window = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(
        fs.readFileSync(path.join(ROOT, "src", "osboot.js"), "utf8"),
        sandbox
    );
    return sandbox.OSBoot;
}

// --- 1. Manifest matches the media directory -----------------------------
{
    assert.ok(fs.existsSync(MANIFEST),
        "media/manifest.json should exist — run node tools/gen-media-manifest.js");

    const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
    assert.ok(Array.isArray(manifest.media),
        "manifest should carry a \"media\" array");

    const expected = expectedMediaList();
    assert.deepStrictEqual(
        JSON.parse(JSON.stringify(manifest.media)).sort(),
        expected,
        "manifest should list exactly the images in media/ " +
        "(regenerate with node tools/gen-media-manifest.js)");

    assert.strictEqual(new Set(manifest.media).size, manifest.media.length,
        "manifest should not contain duplicate urls");
}

// --- 2. The full repo ships every wizard disk/tape image -----------------
{
    const OSBoot = loadOSBoot();
    const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
    const shipped = new Set(manifest.media);

    const missing = OSBoot.BOOT_SCENARIOS
        .filter((s) => !s.paperTape)
        .map((s) => s.url || OSBoot.urlFor(s.device))
        .filter((url) => !shipped.has(url));

    assert.deepStrictEqual(JSON.parse(JSON.stringify(missing)), [],
        "every wizard disk/tape image should ship with the full repo: " +
        missing.join(", "));
}

console.log("media-manifest tests passed");
