import { BookOpen, ArrowLeft, Terminal, Rss, CalendarDays } from 'lucide-react';
import { DEVLOG_POSTS } from '../data/devlogData.ts';

interface DevlogProps {
  lang: 'en' | 'ru';
  onBackToHome: () => void;
  onOpenEmulator: () => void;
}

/**
 * The devlog section of the landing.
 *
 * This is a LIST, not the posts themselves: every post is a static page under
 * devlog/ (generated by tools/build-devlog.js), and this section only links to
 * them. That split is deliberate — a reader arriving from a link aggregator or
 * a search engine must get ordinary HTML, not a React bundle, and the landing
 * must not carry a second copy of the text that could drift from the pages.
 *
 * The data comes from DEVLOG_POSTS, which the same generator writes, so the
 * list and the pages can never disagree about what exists.
 */
export function Devlog({ lang, onBackToHome, onOpenEmulator }: DevlogProps) {
  return (
    <div className="space-y-10">
      {/* Devlog Hero Header */}
      <div className="text-center pt-2 pb-6 border-b border-[#3a3528]/80">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[#524939] bg-[#14120e] text-xs text-[#c8a860] mb-3 font-mono">
          <BookOpen className="w-3.5 h-3.5 text-[#e8d080]" />
          <span>{lang === 'en' ? 'DEVLOG · NOTES FROM THE MACHINE ROOM' : 'DEVLOG · ЗАМЕТКИ ИЗ МАШИННОГО ЗАЛА'}</span>
        </div>

        <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-[#f0e6c8] mb-3">
          {lang === 'en' ? 'yaPDP — Devlog' : 'yaPDP — Девлог'}
        </h1>

        <p className="text-[#c8b890] italic text-sm sm:text-base max-w-2xl mx-auto mb-2 leading-relaxed">
          {lang === 'en'
            ? 'How a PDP-11/70 emulator gets built: the machine room, the Model 33 teletype, the paper tape, and the Soviet SM-4 that started it all.'
            : 'Как строится эмулятор PDP-11/70: машинный зал, телетайп Model 33, перфолента и советская СМ-4, с которой всё началось.'}
        </p>

        <p className="text-xs sm:text-sm text-[#8a7650] font-mono mb-6">
          {lang === 'en'
            ? 'Every post is a standalone page — readable without JavaScript, and available as a feed.'
            : 'Каждая заметка — отдельная страница: читается без JavaScript и доступна в виде ленты.'}
        </p>

        {/* Action buttons */}
        <div className="flex flex-wrap items-center justify-center gap-2.5">
          <button
            onClick={onBackToHome}
            type="button"
            className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-bold uppercase tracking-wider rounded border border-[#524939] bg-[#1e1a14] hover:bg-[#2a241b] text-[#d4c4a0] hover:text-[#f0e6c8] transition-all cursor-pointer"
          >
            <ArrowLeft className="w-3.5 h-3.5 text-[#c8a860]" />
            <span>{lang === 'en' ? 'Back to Overview' : 'Назад к обзору'}</span>
          </button>

          <button
            onClick={onOpenEmulator}
            type="button"
            className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-bold uppercase tracking-wider rounded border border-[#c8a860] bg-gradient-to-b from-[#5a4a30] to-[#3a3528] hover:from-[#6a5838] hover:to-[#4a4030] text-[#f0e6c8] hover:text-[#fff6e0] shadow-sm transition-all cursor-pointer"
          >
            <Terminal className="w-3.5 h-3.5 text-[#e8d080]" />
            <span>{lang === 'en' ? 'Launch Emulator' : 'Запустить эмулятор'}</span>
          </button>

          <a
            href="devlog/feed.xml"
            className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-bold uppercase tracking-wider rounded border border-[#524939] bg-[#1e1a14] hover:bg-[#2a241b] text-[#d4c4a0] hover:text-[#f0e6c8] transition-all"
          >
            <Rss className="w-3.5 h-3.5 text-[#c8a860]" />
            <span>Atom</span>
          </a>
        </div>
      </div>

      {/* The posts, newest first (the generator already sorted them) */}
      <div className="space-y-5">
        {DEVLOG_POSTS.map((post) => (
          <article
            key={post.slug}
            className="p-4 sm:p-5 rounded border border-[#3a3528] bg-[#1c1914] hover:border-[#c8a860]/60 transition-colors"
          >
            <div className="flex items-center gap-2 text-[11px] font-mono text-[#8a7650] mb-2">
              <CalendarDays className="w-3 h-3 text-[#c8a860]" />
              <time dateTime={post.date}>{post.date}</time>
            </div>

            <h2 className="text-lg sm:text-xl font-bold text-[#f0e6c8] mb-2">
              <a
                href={'devlog/' + post.slug + '.html'}
                className="hover:text-[#e8d080] transition-colors"
              >
                {post.title}
              </a>
            </h2>

            <p className="text-sm text-[#c8b890] leading-relaxed mb-3">
              {post.summary}
            </p>

            <a
              href={'devlog/' + post.slug + '.html'}
              className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#c8a860] hover:text-[#e8d080] transition-colors"
            >
              <span>{lang === 'en' ? 'Read the post' : 'Читать'}</span>
              <span aria-hidden="true">→</span>
            </a>
          </article>
        ))}
      </div>

      {/* Where the posts live, for anyone who wants the source */}
      <p className="text-xs text-[#8a7650] font-mono text-center pt-4 border-t border-[#3a3528]/60">
        {lang === 'en'
          ? 'Posts live in docs/devlog/ as Markdown and are generated by tools/build-devlog.js.'
          : 'Заметки лежат в docs/devlog/ в виде Markdown и собираются через tools/build-devlog.js.'}
      </p>
    </div>
  );
}
