// GENERATED by tools/build-devlog.js from docs/devlog/*.md — do not edit.
// The devlog source is Markdown; the posts are static pages, and this file
// is only the landing's list of them.

export interface DevlogPost {
  slug: string;
  date: string;
  title: string;
  summary: string;
}

export const DEVLOG_POSTS: DevlogPost[] = [
  {
    slug: '2026-09-23-bringing-back-the-machine-room',
    date: '2026-09-23',
    title: 'Bringing back the machine room: rebuilding a PDP-11/70 I first met in 1984',
    summary: 'I grew up with Soviet PDP-11 clones. Thirty years later I built a PDP-11/70 emulator in the browser to get that machine room feeling back — and this is what it cost.',
  },
];
