// GENERATED by tools/build-manual.js from docs/manual/*.md — do not edit.
// The manual source is Markdown; this file is one of its two outputs.

export interface ManualSection {
  id: string;
  titleEn: string;
  titleRu: string;
  number?: string;
  subsections?: { id: string; titleEn: string; titleRu: string }[];
}

export const MANUAL_SECTIONS: ManualSection[] = [
  {
    id: 'quick-start',
    // number is positional: generated from _meta.yml order, never stored
    number: '1',
    titleEn: 'Quick Start',
    titleRu: 'Быстрый старт',
    subsections: [
      { id: 'the-magic-wand', titleEn: 'The magic wand', titleRu: 'Волшебная палочка' },
      { id: 'the-classic-way', titleEn: 'The classic way', titleRu: 'Классический способ' },
    ],
  },
  {
    id: 'front-panel',
    // number is positional: generated from _meta.yml order, never stored
    number: '2',
    titleEn: 'The Front Panel (Panel page)',
    titleRu: 'Пультовая панель (страница Panel)',
    subsections: [
      { id: 'front-panel-switch-sequences', titleEn: 'Front panel switch sequences', titleRu: 'Последовательности переключения тумблеров' },
    ],
  },
  {
    id: 'console',
    // number is positional: generated from _meta.yml order, never stored
    number: '3',
    titleEn: 'The Operator Console',
    titleRu: 'Консоль оператора',
    subsections: [
      { id: 'model-33-asr-teletype', titleEn: 'Model 33 ASR teletype', titleRu: 'Телетайп Model 33 ASR' },
      { id: 'vt52-as-the-console', titleEn: 'VT52 as the console', titleRu: 'VT52 в качестве консоли' },
      { id: 'vt100-as-the-console', titleEn: 'VT100 as the console', titleRu: 'VT100 в качестве консоли' },
    ],
  },
  {
    id: 'user-terminals',
    // number is positional: generated from _meta.yml order, never stored
    number: '4',
    titleEn: 'User Terminals (TTY 1 / TTY 2)',
    titleRu: 'Пользовательские терминалы (TTY 1 / TTY 2)',
  },
  {
    id: 'printer',
    // number is positional: generated from _meta.yml order, never stored
    number: '5',
    titleEn: 'The LP11 Line Printer (Printer page)',
    titleRu: 'Построчный принтер LP11 (страница Printer)',
  },
  {
    id: 'vt11',
    // number is positional: generated from _meta.yml order, never stored
    number: '6',
    titleEn: 'The VT11 Vector Display (Display page)',
    titleRu: 'Векторный дисплей VT11 (страница Display)',
  },
  {
    id: 'storage',
    // number is positional: generated from _meta.yml order, never stored
    number: '7',
    titleEn: 'Storage (paper tape, disk & tape images)',
    titleRu: 'Хранилище (перфолента, образы дисков и лент)',
  },
  {
    id: 'machine-state',
    // number is positional: generated from _meta.yml order, never stored
    number: '8',
    titleEn: 'Machine State (STATE button)',
    titleRu: 'Состояние машины (кнопка STATE)',
  },
  {
    id: 'config',
    // number is positional: generated from _meta.yml order, never stored
    number: '9',
    titleEn: 'Configuration (Config page)',
    titleRu: 'Конфигурация (страница Config)',
    subsections: [
      { id: 'equipment', titleEn: 'Equipment', titleRu: 'Оборудование' },
      { id: 'look-sound', titleEn: 'Look & sound', titleRu: 'Вид и звук' },
      { id: 'behaviour', titleEn: 'Behaviour', titleRu: 'Поведение' },
      { id: 'development', titleEn: 'Development', titleRu: 'Разработка' },
    ],
  },
  {
    id: 'guest-oses',
    // number is positional: generated from _meta.yml order, never stored
    number: '10',
    titleEn: 'Guest Operating Systems',
    titleRu: 'Гостевые операционные системы',
  },
  {
    id: 'controls',
    // number is positional: generated from _meta.yml order, never stored
    number: '11',
    titleEn: 'Buttons, Shortcuts & Indicators',
    titleRu: 'Кнопки, сочетания клавиш и индикаторы',
    subsections: [
      { id: 'switching-pages', titleEn: 'Switching pages', titleRu: 'Переключение страниц' },
      { id: 'floating-controls', titleEn: 'Floating controls', titleRu: 'Плавающие элементы управления' },
      { id: 'sidebar-activity-lamps', titleEn: 'Sidebar activity lamps', titleRu: 'Индикаторы активности на боковой панели' },
    ],
  },
  {
    id: 'troubleshooting',
    // number is positional: generated from _meta.yml order, never stored
    number: '12',
    titleEn: 'Troubleshooting',
    titleRu: 'Устранение неполадок',
    subsections: [
      { id: 'an-image-cannot-be-loaded', titleEn: 'An image cannot be loaded', titleRu: 'Образ не загружается' },
    ],
  },
  {
    id: 'desktop',
    // number is positional: generated from _meta.yml order, never stored
    number: '13',
    titleEn: 'The Desktop App',
    titleRu: 'Настольное приложение',
  },
];

export interface GuestOsEntry {
  disk: string;
  name: string;
  bootCommand: string;
  instructionsEn: string;
  instructionsRu: string;
  credentials?: string;
}

// Read from the how-to-boot table in docs/manual(+ru)/guest-oses.md.
export const GUEST_OS_TABLE: GuestOsEntry[] = [
  {
    disk: 'RK0',
    name: 'Unix V5',
    bootCommand: 'boot rk0',
    instructionsEn: 'unix → login as root',
    instructionsRu: 'unix → войти как root',
    credentials: 'root',
  },
  {
    disk: 'RK1',
    name: 'RT-11 v4.0',
    bootCommand: 'BOOT RK1',
    instructionsEn: 'boots immediately to monitor prompt',
    instructionsRu: 'загружается сразу в монитор RT-11',
  },
  {
    disk: 'RK2',
    name: 'RSTS V06C-03',
    bootCommand: 'BOOT RK2',
    instructionsEn: 'wizard answers START at the Option: prompt',
    instructionsRu: 'мастер вводит START на приглашение Option:',
  },
  {
    disk: 'RK3',
    name: 'XXDP (diagnostics)',
    bootCommand: 'BOOT RK3',
    instructionsEn: 'DEC field diagnostic operating system',
    instructionsRu: 'полевая диагностическая система DEC',
  },
  {
    disk: 'RK4',
    name: 'RT-11 3B Distribution',
    bootCommand: 'BOOT RK4',
    instructionsEn: 'RT-11 distribution baseline',
    instructionsRu: 'дистрибутив базовой версии RT-11',
  },
  {
    disk: 'TM0',
    name: 'RSTS 4B-17 (tape)',
    bootCommand: 'BOOT TM0',
    instructionsEn: 'follow ROLLIN restore procedure',
    instructionsRu: 'следуйте процедуре восстановления ROLLIN',
  },
  {
    disk: 'RL0',
    name: 'BSD 2.9',
    bootCommand: 'boot rl0',
    instructionsEn: 'rl(0,0)rlunix → CTRL/D → login root',
    instructionsRu: 'rl(0,0)rlunix → CTRL/D → логин root',
    credentials: 'root',
  },
  {
    disk: 'RL1',
    name: 'RSX-11M v3.2',
    bootCommand: 'BOOT RL1',
    instructionsEn: 'autostarts; enter the date when asked',
    instructionsRu: 'автостарт; введите дату по запросу',
  },
  {
    disk: 'RL2',
    name: 'RSTS/E v7.0',
    bootCommand: 'BOOT RL2',
    instructionsEn: 'wizard answers START at the Option: prompt',
    instructionsRu: 'мастер вводит START на приглашение Option:',
  },
  {
    disk: 'RL3',
    name: 'XXDP (extended)',
    bootCommand: 'BOOT RL3',
    instructionsEn: 'extended diagnostics library',
    instructionsRu: 'расширенная библиотека тестов XXDP',
  },
  {
    disk: 'RP0',
    name: 'ULTRIX-11 V3.1',
    bootCommand: 'boot rp0',
    instructionsEn: 'boots to a single-user shell (multi-user is a known emulator bug)',
    instructionsRu: 'загружается в однопользовательский режим (multi-user — известный баг эмулятора)',
  },
  {
    disk: 'RP1',
    name: 'BSD 2.11',
    bootCommand: 'boot rp1',
    instructionsEn: 'autoboots to multiuser, login root (no password)',
    instructionsRu: 'автозагрузка в многопользовательский режим, логин root (без пароля)',
    credentials: 'root (no password)',
  },
  {
    disk: 'RP2',
    name: 'RSTS/E v9.6',
    bootCommand: 'BOOT RP2',
    instructionsEn: 'boots to the date prompt; then 11,70 / PDP',
    instructionsRu: 'загружается до запроса даты; далее 11,70 / PDP',
    credentials: '11,70 (PDP)',
  },
  {
    disk: 'RP3',
    name: 'RSX-11M v4.6',
    bootCommand: 'BOOT RP3',
    instructionsEn: 'autostarts; enter date/time when asked',
    instructionsRu: 'автостарт; введите дату и время по запросу',
  },
  {
    disk: 'RP4',
    name: 'RSTS/E v10.1',
    bootCommand: 'BOOT RP4',
    instructionsEn: 'boots to the date prompt; then 11,70 / PDP',
    instructionsRu: 'загружается до запроса даты; далее 11,70 / PDP',
    credentials: '11,70 (PDP)',
  },
];

export interface ConfigTabEntry {
  id: string;
  titleEn: string;
  titleRu: string;
  image: string;
  itemsEn: { label: string; desc: string }[];
  itemsRu: { label: string; desc: string }[];
}

// Read from the four CONFIG tabs in docs/manual(+ru)/config.md.
export const CONFIG_TABS_DATA: ConfigTabEntry[] = [
  {
    id: 'equipment',
    titleEn: 'Equipment',
    titleRu: 'Оборудование',
    image: 'assets/images/manual/config-equipment.png',
    itemsEn: [],
    itemsRu: [{ label: 'Console terminal', desc: 'консоль оператора (tty0): телетайп Model 33 ASR, DECscope VT52 или DEC VT100.' }, { label: 'User terminals', desc: 'два пользовательских терминала (TTY 1 / TTY 2), каждый `None | VT52 | VT100` и у каждого своя страница в боковой панели; число терминалов выводится из двух селектов, а TT2 можно заполнить только после TT1.' }, { label: 'Line printer (LP11)', desc: 'установить анимированный построчный принтер LP11 на отдельной странице Printer.' }, { label: 'VT11 graphics display', desc: 'установить терминал векторной графики DEC VT11 на отдельной странице Display.' }, { label: 'Teletype print width', desc: '72 или 80 колонок для консоли Model 33 ASR (телетайп — машина не более чем на 80 колонок).' }, { label: 'Printer width', desc: '72/80/100/132 колонки для страницы принтера LP11.' }, { label: 'Teletype speed', desc: 'authentic (настоящий Model 33 ASR на 110 бод, ~10 знаков/с) или fast — ускоренный темп для разработки.' }, { label: 'Upper Case Only', desc: 'отправлять буквы с физической клавиатуры в верхнем регистре (аутентичный Model 33 ASR); по умолчанию выключено, чтобы проходил нижний регистр (например, имена файлов в 2.11 BSD).' }, { label: 'Force PDP Output Uppercase', desc: 'печатать вывод машины в верхнем регистре (аутентичный Model 33 ASR, который не умеет печатать строчные); по умолчанию включено. Перфолента сохраняет исходный код, а видеотерминал (VT52 или VT100) не затрагивается вовсе — оба печатают оба регистра.' }],
  },
  {
    id: 'look-sound',
    titleEn: 'Look & sound',
    titleRu: 'Вид и звук',
    image: 'assets/images/manual/config-visual.png',
    itemsEn: [],
    itemsRu: [{ label: 'VT100 key click', desc: 'звуковая отдача нажатия клавиш на терминалах VT100; клавиатура DECscope была механической и щёлкать ей нечем, поэтому поле гаснет, когда VT100 не установлен.' }, { label: 'VT100 phosphor', desc: 'трубка VT100: P4 белый (люминофор, с которым он выпускался) или P1 зелёный. DECscope жёстко привязан к P4 — с другим он никогда не продавался.' }, { label: 'VT52 reverse video', desc: 'исторический режим обратного видео DECscope: чёрный текст на белом. Это собственный переключатель DECscope; VT100 показывает инверсный текст только когда программа просит об этом атрибутом SGR 7.' }, { label: 'CRT effects', desc: 'чисто CSS-имитация CRT: мерцание яркости, дрожание люминофора и полоса вертикального срыва.' }, { label: 'Machine hum', desc: 'фоновый гул блока питания и шум вентилятора, пока машина включена.' }, { label: 'Photo backdrop', desc: 'показывать фотографию машинного зала PDP-11 за страницами.' }],
  },
  {
    id: 'behaviour',
    titleEn: 'Behaviour',
    titleRu: 'Поведение',
    image: 'assets/images/manual/config-behaviour.png',
    itemsEn: [],
    itemsRu: [{ label: 'Reboot confirmation', desc: 'спрашивать перед перезагрузкой машины; опцию «Don\'t show this warning anymore» можно вернуть здесь в любой момент.' }, { label: 'Help Me! sticker', desc: 'показывать рукописную памятку оператора о загрузчике на странице Panel.' }, { label: 'Machine power', desc: 'машина включена; выключение обесточивает PDP-11 (POWER LOCK в положении off).' }, { label: 'Auto-boot', desc: 'автоматически запускать загрузку по умолчанию при включении или перезагрузке машины. В диалоге подтверждения перезагрузки есть ярлык к этой опции (её галочка «Start the default bootstrap automatically after reboot»).' }, { label: 'First-run hint', desc: 'повторить приветственный оверлей первого запуска с подсказками по быстрому запуску при следующем входе.' }],
  },
  {
    id: 'development',
    titleEn: 'Development',
    titleRu: 'Разработка',
    image: 'assets/images/manual/config-development.png',
    itemsEn: [],
    itemsRu: [{ label: 'Plain text input instead of the canvas CRT', desc: 'выводить терминал как текстовое поле вместо canvas CRT, что даёт нативное выделение текста и Windows Clipboard (Ctrl+C / Ctrl+V / вставка правой кнопкой) для быстрого ввода исходного кода; при этом теряются атрибуты SGR (жирный/подчёркивание/инверсия). Действует на страницу, поэтому так выводятся и VT52, и VT100.' }],
  },
];

export interface FloatingControlEntry {
  image: string;
  nameEn: string;
  nameRu: string;
  whereEn: string;
  whereRu: string;
  descEn: string;
  descRu: string;
}

// Read from the floating-controls table in docs/manual(+ru)/controls.md.
export const FLOATING_CONTROLS_DATA: FloatingControlEntry[] = [
  {
    image: 'assets/images/manual/btn-magicwand.png',
    nameEn: 'Magic wand', nameRu: 'Волшебная палочка',
    whereEn: 'Top-right corner (every page except Info)', whereRu: 'Правый верхний угол (все страницы, кроме Info)',
    descEn: 'Quick-boot picker — chooses a guest OS, reconfigures, reboots and types the boot/login. See Quick Start.', descRu: 'Список быстрого запуска — выбирает гостевую ОС, перенастраивает, перезагружает и вводит загрузку/логин. См. Быстрый старт.',
  },
  {
    image: 'assets/images/manual/btn-reboot.png',
    nameEn: 'Reboot', nameRu: 'Перезагрузка',
    whereEn: 'Top-left corner, just right of the sidebar (Panel, Console and TTY pages)', whereRu: 'Левый верхний угол, справа от боковой панели',
    descEn: 'Round button with a restart icon. Restarts the machine; when Auto-boot is enabled it also boots the built-in default loader. By default a confirmation dialog asks first, with a "Don\'t show this warning anymore" option. The dialog also carries an Auto-boot shortcut: tick Start the default bootstrap automatically after reboot to run the default loader after this reboot — it is the CONFIG Auto-boot option itself, persists, and stays in sync with the CONFIG page checkbox. Without Auto-boot the machine halts after the reboot. The confirmation dialog is shown below.', descRu: 'Круглая кнопка со значком рестарта. Перезапускает машину; при включённом Auto-boot загружает и встроенный загрузчик по умолчанию. По умолчанию сначала запрашивается подтверждение, с опцией «Don\'t show this warning anymore». Без Auto-boot после перезагрузки машина останавливается.',
  },
  {
    image: 'assets/images/manual/btn-mute.png',
    nameEn: 'Mute', nameRu: 'Без звука (Mute)',
    whereEn: 'Bottom-left corner, just right of the sidebar', whereRu: 'Левый нижний угол, справа от боковой панели',
    descEn: 'Round button that toggles all sounds at once — hum, teletype/LP11, paper feed/tear, key clicks and the bell. State is persisted with the rest of the configuration.', descRu: 'Круглая кнопка, выключающая все звуки разом — гул, телетайп/LP11, подача и отрыв бумаги, щелчки клавиш и звонок. Состояние сохраняется вместе с остальной конфигурацией.',
  },
  {
    image: 'assets/images/manual/btn-fullscreen.png',
    nameEn: 'Fullscreen', nameRu: 'Полноэкранный режим',
    whereEn: 'Bottom-right corner of the window', whereRu: 'Правый нижний угол окна',
    descEn: 'Floating button that hides the browser/system chrome (address bar, OS window frame, taskbar) while leaving the emulator UI untouched. Press again or Esc to return.', descRu: 'Плавающая кнопка, скрывающая интерфейс браузера и системы (адресную строку, рамку окна ОС, панель задач), не трогая интерфейс эмулятора. Нажмите ещё раз или Esc, чтобы вернуться.',
  },
  {
    image: 'assets/images/manual/btn-zoom.png',
    nameEn: 'Terminal zoom', nameRu: 'Масштаб терминала',
    whereEn: 'Bottom-right corner, left of the fullscreen button', whereRu: 'Правый нижний угол, слева от кнопки полного экрана',
    descEn: 'Floating button that hides the terminal cabinet and grows the tube to the largest 4:3 box the window allows. The state is remembered per terminal.', descRu: 'Плавающая кнопка, скрывающая корпус терминала и увеличивающая экран до максимального размера 4:3, какой позволяет окно. Состояние запоминается для каждого терминала.',
  },
];
