#!/usr/bin/env node
/**
 * yaPDP — version sync.
 *
 * Generates src/version.js from package.json so the browser app has a single
 * source of truth for the user-visible version string (the sidebar marker
 * and the Info page "About" block).
 *
 * Usage:
 *   node tools/sync-version.js
 *   npm run version:sync
 *
 * Run it whenever package.json's "version" field changes; the generated file
 * is checked into git.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
const version = String(pkg.version || "0.0.0");

const out = `// Generated by tools/sync-version.js from package.json — do not edit by hand.
// Single source of truth for the user-visible version string (sidebar
// marker, Info page "About" block). Regenerate with: npm run version:sync
window.yaPDP_VERSION = ${JSON.stringify(version)};
`;

const target = path.join(ROOT, "src", "version.js");
fs.writeFileSync(target, out);
console.log(`src/version.js <- package.json version ${version}`);
