#!/usr/bin/env node
/**
 * yaPDP — version sync.
 *
 * package.json is the single source of truth for the app version; this
 * script pushes it into every other place the version string lives, so a
 * release bump is exactly two steps: edit package.json, run `npm run
 * version:sync`.
 *
 * Targets updated in place:
 *   src/version.js                    — browser UI (sidebar marker, About block)
 *   src-tauri/tauri.conf.minimal.json — installer version (Minimal build)
 *   src-tauri/tauri.conf.full.json    — installer version (Full build)
 *   src-tauri/Cargo.toml              — Rust crate version
 *
 * The generated/gitignored src-tauri/tauri.conf.json is produced from the
 * variant files by tools/build-desktop.js, so it needs no direct handling.
 *
 * Usage:
 *   node tools/sync-version.js
 *   npm run version:sync
 *
 * Idempotent: re-running with an unchanged package.json version writes the
 * same values back (no-op diff).
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
const version = String(pkg.version || "0.0.0");

let changed = 0;
function writeIfDiffers(file, text) {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (existing !== text) {
        fs.writeFileSync(file, text);
        console.log(`${path.relative(ROOT, file)} -> version ${version}`);
        changed++;
    }
}

// 1. src/version.js — generated, committed
const versionJs = `// Generated by tools/sync-version.js from package.json — do not edit by hand.
// Single source of truth for the user-visible version string (sidebar
// marker, Info page "About" block). Regenerate with: npm run version:sync
window.YAPDP_VERSION = ${JSON.stringify(version)};
`;
writeIfDiffers(path.join(ROOT, "src", "version.js"), versionJs);

// 2/3. Tauri installer configs (both variants) — committed, hand-maintained
for (const variant of ["minimal", "full"]) {
    const file = path.join(ROOT, "src-tauri", `tauri.conf.${variant}.json`);
    if (!fs.existsSync(file)) {
        console.error(`WARN: ${path.relative(ROOT, file)} not found, skipped`);
        continue;
    }
    const conf = JSON.parse(fs.readFileSync(file, "utf8"));
    if (conf.version !== version) {
        conf.version = version;
        fs.writeFileSync(file, JSON.stringify(conf, null, 4) + "\n");
        console.log(`${path.relative(ROOT, file)} -> version ${version}`);
        changed++;
    }
}

// 4. Cargo.toml crate version
const cargoFile = path.join(ROOT, "src-tauri", "Cargo.toml");
if (fs.existsSync(cargoFile)) {
    const cargo = fs.readFileSync(cargoFile, "utf8");
    const next = cargo.replace(
        /^version\s*=\s*"[^"]*"/m,
        `version = "${version}"`
    );
    if (next !== cargo) {
        fs.writeFileSync(cargoFile, next);
        console.log(`${path.relative(ROOT, cargoFile)} -> version ${version}`);
        changed++;
    }
}

if (changed === 0) {
    console.log(`version ${version} already in sync everywhere`);
}
