#!/usr/bin/env node
/**
 * Build the Tauri desktop app (MSI + NSIS + portable exe) with
 * `cargo tauri build`.
 *
 * Runs inside src-tauri/ so the Tauri CLI picks up the (gitignored)
 * src-tauri/tauri.conf.json generated by tools/build-desktop.js. The cwd is
 * set here so the command is portable regardless of the invoking shell.
 *
 * Usage: node tools/tauri-build.js
 */
"use strict";

const { spawnSync } = require("child_process");
const path = require("path");

const tauriDir = path.join(__dirname, "..", "src-tauri");

console.log(`cargo tauri build (in ${tauriDir})`);

const result = spawnSync("cargo", ["tauri", "build"], {
    cwd: tauriDir,
    stdio: "inherit",
    shell: process.platform === "win32",
});

process.exit(result.status === null ? 1 : result.status);
