#!/usr/bin/env node
/**
 * Build / package the Tauri desktop app (deb/rpm/AppImage/msi/nsis).
 *
 * Runs inside src-tauri/ so the Tauri CLI picks up the (gitignored)
 * src-tauri/tauri.conf.json generated by tools/build-desktop.js. The cwd is
 * set here so the command is portable regardless of the invoking shell.
 *
 * Two modes:
 *   default                    -> `cargo tauri build`    (cargo compile + bundle)
 *   --bundle-only              -> `cargo tauri bundle`  (package the ALREADY
 *                                                       built target/release
 *                                                       binary, no recompile)
 *
 * The release CI compiles Rust once per OS (build-rust job), downloads that
 * target/release, then runs this tool in --bundle-only mode for each
 * minimal/full variant. Keep the default (compile+bundle) intact for local
 * builds via `npm run desktop:*`.
 *
 * Usage: node tools/tauri-build.js [--bundle-only]
 */
"use strict";

const { spawnSync } = require("child_process");
const path = require("path");

const tauriDir = path.join(__dirname, "..", "src-tauri");

const args = process.argv.slice(2);
const bundleOnly = args.includes("--bundle-only");
const variant = args.indexOf("--variant") !== -1
    ? args[args.indexOf("--variant") + 1]
    : null;

// `cargo tauri bundle` needs the built app binary. It does NOT invoke cargo
// itself; it only reads tauri.conf.json + target/release to produce bundles.
const cmdArgs = bundleOnly ? ["tauri", "bundle"] : ["tauri", "build"];
const what = (bundleOnly ? "cargo tauri bundle" : "cargo tauri build") +
    (variant ? ` (${variant})` : "");

console.log(`${what} (in ${tauriDir})`);

const result = spawnSync("cargo", cmdArgs, {
    cwd: tauriDir,
    stdio: "inherit",
    shell: process.platform === "win32",
});

process.exit(result.status === null ? 1 : result.status);
