/**
 * yaPDP — Quick boot wizard (magic wand)
 *
 * A small button pinned to the top-right corner of the Panel page opens a
 * modal dialog (shared modal-* style) listing every guest OS scenario from
 * osboot.js. Picking one boots the machine into that OS with a single click —
 * and, where credentials are known, types the login for you.
 *
 * Flow:
 *   1. If the OS needs a different machine profile (teletype vs VT52 console,
 *      LP11 printer present), the wizard persists the pending boot, applies
 *      the profile via Config.set() and reloads — devices are registered at
 *      load time, so a layout change needs a reload (same as CONFIG Apply).
 *      After the reload the wizard resumes the boot automatically.
 *   2. Switch to the operator console page (teletype or VT52 console).
 *   3. Reboot the machine (boot()) so the loader prints the @ prompt.
 *   4. Type `boot <dev>`, then each follow-up step (kernel name, Ctrl-D,
 *      login/password) with a delay that respects the configured teletype
 *      speed.
 *
 * Prompt-aware steps: a step with `waitFor` (e.g. "login:") is not sent on a
 * timer — the wizard watches the console output and types only once the
 * prompt appears (with a generous timeout fallback), so slow boots with lots
 * of output (2.11 BSD) still reach the login. The console output is captured
 * through window.__consoleOutputHook, which iopage.js feeds for every console
 * character (both teletype and VT52 console).
 *
 * Console input goes through the same global queue the physical keyboard
 * uses (window.dlReceiveQueue(0, bytes)), so it works for both the Model 33
 * ASR teletype and the VT52 console. Enter = 13, Ctrl-D = 4.
 *
 * Must be loaded AFTER osboot.js, config.js, pdp11-panel.js (switchPage) and
 * bootcode.js (boot); BEFORE pdp11-app.js.
 */
"use strict";

var QuickBoot = (function () {
    var overlay = null;

    // Pending boot device persisted across a config-driven reload.
    var PENDING_KEY = "yapdp.quickboot.pending";

    // Build manifest (media/manifest.json, generated by
    // tools/gen-media-manifest.js): logical urls of the images this
    // deployment ships. null while unknown or absent — the wizard then
    // offers every scenario (previous behaviour), so ad-hoc hosts and
    // file:// deployments keep working unchanged.
    var manifestList = null;
    var manifestPromise = null;

    // Fetch the build manifest once. Resolves to the image-url list, or null
    // when the deployment has no manifest (or fetch is unavailable). The
    // promise is shared so the wizard and the Info page see the same answer.
    function fetchManifest() {
        if (typeof fetch !== "function" || typeof document === "undefined") {
            return Promise.resolve(null);
        }
        return fetch("media/manifest.json", { cache: "no-store" })
            .then(function (r) { return r.ok ? r.json() : null; })
            .then(function (m) {
                manifestList = (m && Array.isArray(m.media)) ? m.media : null;
                return manifestList;
            })
            .catch(function () { manifestList = null; return null; })
            .then(function () {
                // The dialog may already be open when the manifest arrives
                // (slow host); re-render so the list settles on the truth.
                if (overlay && overlay.classList.contains("visible")) updateList();
                return manifestList;
            });
    }

    // Console output sniffer: iopage.js feeds every console character through
    // window.__consoleOutputHook; we keep the tail so prompt-waiting steps can
    // detect "login:" etc. instead of guessing timings.
    var MAX_BUFFER = 4096;
    var outputBuffer = "";

    // ------------------------------------------------------------------
    // Pure helpers (no DOM) — unit-testable in Node
    // ------------------------------------------------------------------

    // Which console page hosts the operator console for the given config.
    function consolePageFor(cfg) {
        var t = cfg && cfg.consoleType;
        // Both graphical terminals share the vt52-console page; the teletype has
        // its own.
        return (t === "vt52" || t === "vt100") ? "vt52-console" : "teletype";
    }

    // Delay between typed steps; the authentic 110-baud teletype is slow, so
    // it gets more time for the guest to reach the next prompt.
    function stepDelayMs(speed) {
        return (speed === "authentic") ? 1600 : 800;
    }

    // Console bytes for one scenario step: plain text + Enter, or ^D (4).
    function stepBytes(step) {
        if (step && step.ctrlD) return [4];
        var text = (step && step.send) ? step.send : "";
        return OSBoot.stringToBytes(text).concat([13]);
    }

    // True when the accumulated console output contains needle.
    function bufferContains(buffer, needle) {
        return !!needle && buffer.indexOf(needle) !== -1;
    }

    // The hardware profile a scenario requires; every scenario declares it
    // explicitly, with null meaning "keep the user's current setting".
    function profileOf(scenario) {
        return (scenario && scenario.hardware) || {};
    }

    // Merge a scenario's hardware profile over the current config. Keys set
    // to null in the profile are left untouched. Pure — unit-testable.
    function mergeHardware(cfg, profile) {
        var out = {};
        Object.keys(cfg || {}).forEach(function (k) { out[k] = cfg[k]; });
        if (profile.console) out.consoleType = profile.console;
        if (typeof profile.printer === "boolean") out.printer = profile.printer;
        if (typeof profile.vt11 === "boolean") out.vt11 = profile.vt11;
        if (typeof profile.forceUpperCaseOut === "boolean") {
            out.forceUpperCaseOut = profile.forceUpperCaseOut;
        }
        return out;
    }

    // True when the current config differs from the profile's requirements.
    // Only LAYOUT keys count: they are registered at load time, so a change
    // needs a page reload. forceUpperCaseOut is a live option (the console
    // printer reads it per printed character), so it must NOT force a reload —
    // see liveProfile()/launch().
    function hardwareDirty(cfg, profile) {
        if (!profile) return false;
        if (profile.console && cfg.consoleType !== profile.console) return true;
        if (typeof profile.printer === "boolean" &&
            cfg.printer !== profile.printer) return true;
        if (typeof profile.vt11 === "boolean" &&
            cfg.vt11 !== profile.vt11) return true;
        return false;
    }

    // Persist the profile's LIVE options (those that need no reload) and
    // report whether any of them actually changed. Pure — unit-testable.
    function liveProfile(cfg, profile) {
        var next = mergeHardware(cfg, profile);
        var changed = !!cfg && next.forceUpperCaseOut !== cfg.forceUpperCaseOut;
        return { changed: changed, forceUpperCaseOut: next.forceUpperCaseOut };
    }

    // Human-readable summary of the hardware the machine will actually boot
    // with for a scenario: the scenario's profile merged over the current
    // config (null profile keys keep the user's current setting). Always
    // states the console type and whether the LP11 printer is present.
    // Pure — unit-testable in Node.
    function requirementText(profile, cfg) {
        var merged = mergeHardware(cfg, profile);
        var parts = [];
        if (merged.consoleType === "vt100") parts.push("VT100 console");
        else if (merged.consoleType === "vt52") parts.push("VT52 console");
        else parts.push("teletype console");
        parts.push(merged.printer ? "LP11 printer" : "no printer");
        // Only positive requirements are shown — "no VT11" would be printed
        // for nearly every OS and just add noise (VT11 is off by default).
        if (merged.vt11 === true) parts.push("VT11 display");
        return parts.join(" · ");
    }

    // The raw key carried by a deep link from the landing OS galleries:
    // ?boot=<device>, or null only when the parameter is absent altogether.
    //
    // An EMPTY value is NOT "nobody asked": "?boot=" with nothing after it (or
    // a bare "?boot") is a link that lost its key — a broken template on the
    // page that emitted it — and the visitor gets the same explanation as for a
    // key that names no scenario. That is why this returns "" rather than null
    // for those, and why the caller tests for null rather than for truthiness.
    //
    // Kept apart from deviceFromSearch() so the page can tell "nobody asked for
    // anything" (say nothing) from "somebody asked for something we cannot do"
    // (say so). A dangling %-escape comes back as typed: it is about to be
    // shown to the person who typed it, not evaluated.
    // Pure — unit-testable in Node.
    function bootKeyFromSearch(search) {
        var s = search || "";
        var valued = /[?&]boot=([^&]*)/.exec(s);
        if (valued) {
            try {
                return decodeURIComponent(valued[1]);
            } catch (err) {
                return valued[1];
            }
        }
        // A bare "?boot" (no "=" at all) is the same broken link.
        return /[?&]boot(?:&|$)/.test(s) ? "" : null;
    }

    // The device key carried by that deep link. The key names a QuickBoot
    // SCENARIO, not a disk URL, so launch() applies the whole thing — the boot
    // command, the typed steps, the paper tape and the scenario's hardware
    // profile (console, printer, VT11, force-upper). An unknown or malformed
    // key returns null: the page opens, nothing throws, and nothing boots that
    // nobody asked for. The wizard explains the miss instead — see init().
    // Pure — unit-testable in Node.
    function deviceFromSearch(search) {
        var device = bootKeyFromSearch(search);
        if (device === null) return null;
        return (typeof OSBoot !== "undefined" && OSBoot.scenarioFor(device))
            ? device : null;
    }

    // A key shown back to the visitor. A URL is not a place to trust, so the
    // text is tamed before it reaches the dialog:
    //   - control characters, line separators and bidi overrides become "?": a
    //     key of newlines would render as a multi-line paragraph, and U+202E
    //     would silently reorder what the visitor reads;
    //   - the cut is by CODE POINTS, not UTF-16 units, so a key ending in an
    //     emoji is not sliced through a surrogate pair and left as half a
    //     character.
    // Plain text only — the dialog is built with createElement/textContent, so
    // nothing here has to be escaped.
    function boundKey(key) {
        var s = String(key)
            .replace(/[\u0000-\u001F\u007F-\u009F\u2028\u2029\u202A-\u202E\u2066-\u2069]/g, "?");
        var points = Array.from(s);
        return points.length > 40 ? points.slice(0, 40).join("") + "…" : s;
    }

    // ------------------------------------------------------------------
    // Overlay DOM (browser only — not exercised by the Node tests)
    // ------------------------------------------------------------------

    function hide() {
        if (overlay) overlay.classList.remove("visible");
    }

    // --- "Autoloading in progress" balloon ------------------------------
    // A small toast shown while the wizard types the boot sequence, warning
    // the operator not to touch the teletype/keyboard. It disappears when the
    // sequence finishes or the user intervenes (any key press).
    var balloon = null;

    function ensureBalloon() {
        if (balloon) return balloon;
        balloon = document.createElement("div");
        balloon.id = "quick-boot-balloon";
        balloon.className = "quickboot-balloon";
        balloon.textContent =
            "Autoloading in progress — don't touch the teletype/keyboard";
        document.body.appendChild(balloon);
        return balloon;
    }

    function showBalloon() {
        if (typeof document === "undefined") return;
        ensureBalloon().classList.add("visible");
    }

    function hideBalloon() {
        if (balloon) balloon.classList.remove("visible");
    }

    // Autoload abort token: bumped by every new launch() and by abortAutoload().
    // Timers capture the token they belong to and stop as soon as it no longer
    // matches, so a failed image load (imgerror.js) or a second launch can
    // neither leave the balloon up nor keep typing stale steps into a console
    // that is not responding.
    var autoloadToken = 0;

    function abortAutoload() {
        autoloadToken++;
        hideBalloon();
    }

    // Scenarios the wizard should offer right now. With no availability
    // information yet (no manifest, nothing mounted in DataLoader) the full
    // list is shown — the server may still have every image. Once the
    // manifest resolves (or images are mounted), only scenarios whose image
    // is in the manifest and/or mounted are listed (see OSBoot.filterAvailable).
    function currentScenarios() {
        var all = (typeof OSBoot !== "undefined" && OSBoot.BOOT_SCENARIOS)
            ? OSBoot.BOOT_SCENARIOS : [];
        if (typeof OSBoot === "undefined" ||
            typeof OSBoot.filterAvailable !== "function") return all;
        var mounted = (typeof DataLoader !== "undefined" &&
                       typeof DataLoader.list === "function")
            ? DataLoader.list() : [];
        if (!manifestList && (!mounted || mounted.length === 0)) return all;
        return OSBoot.filterAvailable(manifestList, mounted);
    }

    function updateList() {
        var listEl = overlay.querySelector(".quickboot-list");
        if (!listEl) return;
        listEl.innerHTML = "";
        var scenarios = currentScenarios();
        var cfg = (typeof Config !== "undefined" && Config.get)
            ? Config.get() : null;
        scenarios.forEach(function (s) {
            var btn = document.createElement("button");
            btn.type = "button";
            btn.className = "quickboot-option";
            btn.setAttribute("data-quickboot-device", s.device);
            var name = document.createElement("span");
            name.className = "quickboot-name";
            name.textContent = s.label;
            var cmd = document.createElement("span");
            cmd.className = "quickboot-cmd";
            cmd.textContent = s.boot + (s.autoLogin ? "  + auto-login" : "");
            btn.appendChild(name);
            btn.appendChild(cmd);
            var req = requirementText(profileOf(s), cfg);
            if (req) {
                var reqEl = document.createElement("span");
                reqEl.className = "quickboot-req";
                reqEl.textContent = req;
                btn.appendChild(reqEl);
            }
            btn.addEventListener("click", function () {
                launch(s.device);
            });
            listEl.appendChild(btn);
        });
    }

    // --- "No such scenario" dialog ---------------------------------------
    // A deep link asking for a key this build does not have — a stale link from
    // an article, a typo, a renamed scenario — is an explicit request that
    // cannot be met. It gets the same treatment as a failed image fetch: the
    // .modal-box.error shell from css/pdp11.css, one "Got it" to dismiss and
    // one action that leads somewhere useful (the wizard's list). Built with
    // createElement/textContent, the way imgerror.js builds its overlay, so the
    // key — which comes from a URL nobody validated — is data, never markup.
    var linkOverlay = null;

    function hideNoScenario() {
        if (linkOverlay) linkOverlay.classList.remove("visible");
    }

    function showNoScenario(key) {
        if (typeof document === "undefined") return;
        if (!linkOverlay) {
            linkOverlay = document.createElement("div");
            linkOverlay.id = "quickboot-link-error";
            linkOverlay.className = "modal-overlay";
            linkOverlay.addEventListener("click", function (e) {
                if (e.target === linkOverlay) {
                    hideNoScenario();
                    return;
                }
                var action = e.target.getAttribute &&
                    e.target.getAttribute("data-bootlink-action");
                if (action === "wizard") {
                    hideNoScenario();
                    show();
                } else if (action === "close" ||
                        (e.target.closest && e.target.closest(".modal-close"))) {
                    hideNoScenario();
                }
            });
            document.body.appendChild(linkOverlay);
        }

        var box = document.createElement("div");
        box.className = "modal-box error";

        var title = document.createElement("span");
        title.className = "modal-title";
        title.textContent = "Quick boot scenario not found";
        box.appendChild(title);

        var intro = document.createElement("p");
        intro.className = "modal-intro";
        var tail = " — the machine is idle, exactly as if the page had been " +
            "opened without it. Pick a guest OS from the quick-boot list, or " +
            "type the boot command yourself at the @ prompt.";
        // An empty key is its own case: the link arrived without one, and
        // naming it would print an empty <code> element.
        if (key === "") {
            intro.appendChild(document.createTextNode(
                "The quick-boot link arrived with no key at all, so nothing " +
                "was booted" + tail));
        } else {
            intro.appendChild(document.createTextNode("The quick-boot key "));
            var code = document.createElement("code");
            code.textContent = boundKey(key);
            intro.appendChild(code);
            intro.appendChild(document.createTextNode(
                " names no scenario in this build, so nothing was booted" + tail));
        }
        box.appendChild(intro);

        // Dismiss first, then the "fix it" action — matching the other modals
        // (and imgerror's "Got it" → "Open Storage" order).
        var gotItBtn = document.createElement("button");
        gotItBtn.type = "button";
        gotItBtn.className = "modal-close";
        gotItBtn.setAttribute("data-bootlink-action", "close");
        gotItBtn.textContent = "Got it";
        box.appendChild(gotItBtn);

        var wizardBtn = document.createElement("button");
        wizardBtn.type = "button";
        wizardBtn.className = "modal-close";
        wizardBtn.setAttribute("data-bootlink-action", "wizard");
        wizardBtn.textContent = "Choose a guest OS";
        box.appendChild(wizardBtn);

        linkOverlay.innerHTML = "";
        linkOverlay.appendChild(box);
        linkOverlay.classList.add("visible");
    }

    function show() {
        if (!overlay) {
            overlay = document.createElement("div");
            overlay.id = "quick-boot-overlay";
            overlay.className = "modal-overlay";
            overlay.addEventListener("click", function (e) {
                if (e.target === overlay ||
                    (e.target.closest && e.target.closest(".quickboot-close"))) {
                    hide();
                }
            });
            document.body.appendChild(overlay);
        }
        overlay.innerHTML =
            '<div class="modal-box quickboot-box">' +
                '<span class="modal-title">Quick boot</span>' +
                '<p class="modal-intro">Pick a guest OS to boot it in one ' +
                    'click — credentials are typed automatically where known, ' +
                    'and the machine is reconfigured to suit the OS.</p>' +
                '<div class="quickboot-list"></div>' +
                '<button type="button" class="modal-close quickboot-close">Close</button>' +
            '</div>';
        updateList();
        overlay.classList.add("visible");
    }

    // --- Console output capture -----------------------------------------

    function pushOutput(ch) {
        outputBuffer += String.fromCharCode(ch & 0x7F);
        if (outputBuffer.length > MAX_BUFFER) {
            outputBuffer = outputBuffer.slice(outputBuffer.length - MAX_BUFFER);
        }
    }

    function clearOutput() {
        outputBuffer = "";
    }

    function outputContains(needle) {
        return bufferContains(outputBuffer, needle);
    }

    // --- Typing / orchestration -----------------------------------------

    function sendBytes(bytes) {
        // In-page feature: use the internal bridge; the legacy window
        // surface is ?bridge=1-gated for external tooling.
        var bridge = window.__yapdpBridge;
        if (bridge && bridge.dlReceiveQueue) {
            bridge.dlReceiveQueue(0, bytes);
        } else if (typeof window.dlReceiveQueue === "function") {
            window.dlReceiveQueue(0, bytes);
        }
    }

    // Wait budget for a prompt; after this the step is sent anyway so the
    // sequence never stalls on a guest that does not print the expected text.
    var WAIT_TIMEOUT_MS = 45000;
    var WAIT_POLL_MS = 200;

    // First step (boot) needs extra time for the @ prompt to appear.
    function delayFor(index, base) {
        return (index === 0) ? base * 2 : base;
    }

    function runSteps(steps, index, base, token) {
        // A stale token means this sequence was aborted or superseded by a
        // newer launch — stop silently (abortAutoload already hid the balloon).
        if (token !== autoloadToken) return;
        if (index >= steps.length) {
            // All steps typed — the autoload is finished.
            hideBalloon();
            return;
        }
        var step = steps[index];
        if (step.wait) {
            // Pure delay step (no input): e.g. let a guest settle before
            // the next prompt (BSD 2.9's getty flushes input received
            // before it finished opening the console).
            setTimeout(function () {
                if (token !== autoloadToken) return; // aborted or superseded
                runSteps(steps, index + 1, base, token);
            }, step.wait);
        } else if (step.waitFor) {
            waitForPrompt(steps, index, base, step.waitFor, Date.now(), token);
        } else {
            setTimeout(function () {
                if (token !== autoloadToken) return; // aborted or superseded
                sendBytes(stepBytes(step));
                runSteps(steps, index + 1, base, token);
            }, delayFor(index, base));
        }
    }

    function waitForPrompt(steps, index, base, needle, startedAt, token) {
        if (token !== autoloadToken) return; // aborted or superseded
        if (outputContains(needle) || Date.now() - startedAt > WAIT_TIMEOUT_MS) {
            // Prompt seen (or timed out): optionally settle, then send the
            // input and move on.
            var settle = steps[index].wait || 0;
            setTimeout(function () {
                if (token !== autoloadToken) return; // aborted or superseded
                sendBytes(stepBytes(steps[index]));
                setTimeout(function () {
                    runSteps(steps, index + 1, base, token);
                }, base);
            }, settle);
            return;
        }
        setTimeout(function () {
            waitForPrompt(steps, index, base, needle, startedAt, token);
        }, WAIT_POLL_MS);
    }

    // Wipe the operator console buffers so every wizard boot starts "on a
    // fresh page": the teletype paper and LP11 paper are cleared, and every
    // VT52 screen (console + user terminals) is cleared.
    function clearConsole() {
        var g60 = (typeof window !== "undefined") ? window.g60printer : null;
        if (g60 && typeof g60.clear === "function") g60.clear();
        // Rewind the ASR paper tape so the boot banner punches onto a fresh
        // tape, matching the "on a fresh page" teletype paper reset.
        if (typeof window !== "undefined" && window.paperTape &&
            typeof window.paperTape.clear === "function") {
            window.paperTape.clear();
        }
        if (typeof window !== "undefined" && window.lp11G60Printer &&
            typeof window.lp11G60Printer.clear === "function") {
            window.lp11G60Printer.clear();
        }
        if (typeof window !== "undefined" && typeof window.vt52Get === "function") {
            for (var u = 0; u <= 2; u++) {
                var t = window.vt52Get(u);
                if (t && typeof t.clearScreen === "function") t.clearScreen();
            }
        }
    }

    // Put the operator's console controls into the state a boot needs. The
    // wizard types its steps straight into the MACHINE (the DL11 receive
    // queue), but everything the machine answers is printed only on LINE: with
    // the CCU left in OFF or LOCAL the paper stays blank and a perfectly booted
    // guest reads as a hung machine (g60ConsoleWrite ignores output off line).
    // A tape feeding under its own power is the other interference — in START,
    // and in AUTO where the guest's own X-ON can start it, the reader would
    // inject bytes into the middle of the boot. Returns the actions taken, so
    // the contract is testable without a DOM (see tests/quickboot-console.test.js).
    function consoleWorkingState(state, api) {
        var done = [];
        if (!state || !api) return done;
        if (state.ttyMode !== "line" && typeof api.setTtyMode === "function") {
            api.setTtyMode("line");
            done.push("line");
        }
        if ((state.readerMode === "start" || state.readerMode === "auto") &&
            typeof api.setReaderMode === "function") {
            api.setReaderMode("stop");
            done.push("reader-stop");
        }
        return done;
    }

    // Type the boot sequence for a scenario. `force` skips the hardware
    // profile check — used when resuming a pending boot after a reload.
    function launch(device, force) {
        var scenario = (typeof OSBoot !== "undefined" && OSBoot.scenarioFor)
            ? OSBoot.scenarioFor(device) : null;
        if (!scenario) return;

        var cfg = (typeof Config !== "undefined" && Config.get)
            ? Config.get() : null;
        var profile = profileOf(scenario);

        // Live option first: the force-upper flag needs no reload (the console
        // printer reads it per character), so it is applied straight away and
        // can never trigger the layout reload below on its own.
        var live = liveProfile(cfg, profile);
        if (live.changed && typeof Config.set === "function") {
            Config.set({ forceUpperCaseOut: live.forceUpperCaseOut });
        }

        // Apply the machine profile if the current config differs. Device
        // registration happens at load time, so a layout change reloads the
        // page (same as the CONFIG Apply button); the boot resumes afterwards.
        if (!force && cfg && hardwareDirty(cfg, profile)) {
            try {
                if (window.localStorage) window.localStorage.setItem(PENDING_KEY, device);
            } catch (err) { /* ignore */ }
            if (typeof Config.set === "function") {
                Config.set(mergeHardware(cfg, profile));
            }
            // This is an intentional reload: suppress the beforeunload warning
            // that would otherwise ask "Reload site?" (the CONFIG form is not
            // in sync with the freshly applied profile).
            window.__allowConfigReload = true;
            window.location.reload();
            return;
        }

        hide();

        // Select the paper tape (if any) and rewind it so the boot loader
        // reads it from the start.
        if (scenario.paperTape) {
            var ptrSelect = (typeof document !== "undefined")
                ? document.getElementById("ptr") : null;
            if (ptrSelect) ptrSelect.value = scenario.paperTape;
            if (typeof window.ptrRewindTape === "function") window.ptrRewindTape();
        }

        // Show the operator console — or the scenario's target page (e.g. the
        // VT11 Display page for Lunar Lander) — so the output is visible.
        if (typeof switchPage === "function") {
            switchPage(scenario.page || consolePageFor(cfg));
        }

        // Start "on a fresh page": clear teletype/LP11 paper and VT52 screens
        // before the reboot, so the boot banner lands on clean output.
        clearConsole();

        // ... and with a console able to SHOW that output at all: the teletype
        // on LINE, and no tape feeding bytes of its own while the steps are
        // typed. Both are the operator's controls, so the knob visibly turns.
        consoleWorkingState(
            { ttyMode: window.ttyMode, readerMode: window.ttyReaderMode },
            {
                setTtyMode: (typeof setTtyMode === "function") ? setTtyMode : null,
                setReaderMode: (typeof setReaderMode === "function") ? setReaderMode : null
            });

        // Reboot the machine so the boot loader reaches the @ prompt.
        if (typeof boot === "function") boot();

        // Forget any old console output so waitFor cannot match stale text.
        clearOutput();

        var base = stepDelayMs(cfg && cfg.teletypeSpeed);
        var steps = [{ send: scenario.boot }];
        var seq = scenario.steps || []; // paper tapes have no follow-up steps
        for (var i = 0; i < seq.length; i++) {
            steps.push(seq[i]);
        }
        // Own token for this run: a newer launch or an abort cancels it.
        var token = ++autoloadToken;
        showBalloon();
        runSteps(steps, 0, base, token);
    }

    // --- Wiring: the magic-wand button lives in pdp11.html on the Panel page
    function init() {
        if (typeof document === "undefined") return; // Node tests

        // Always wire the button — a deferred resume below must not leave it
        // dead, otherwise the wizard cannot be re-opened after a reload.
        // Wrapped, not passed directly: show() now takes the key of a scenario
        // nobody has, and a listener would hand it the click event instead.
        var btn = document.getElementById("quick-boot-btn");
        if (btn) btn.addEventListener("click", function () { show(); });

        // Resume a boot that was deferred by a config-driven reload.
        var pending = null;
        try {
            if (window.localStorage) pending = window.localStorage.getItem(PENDING_KEY);
        } catch (err) { /* ignore */ }

        // A deep link from the landing OS galleries. It is read once and
        // dropped from the URL right away: a hardware-profile change below
        // reloads the page, and the PENDING KEY — not the parameter — is what
        // brings the boot back. Leaving the parameter in place would start the
        // same scenario a second time after that reload.
        var search = (typeof location !== "undefined") ? location.search : "";
        var requested = bootKeyFromSearch(search);
        var linked = deviceFromSearch(search);
        if (linked) {
            try {
                history.replaceState(null, "",
                    location.pathname + location.hash);
            } catch (err) { /* ignore: the boot below still runs exactly once */ }
        }

        if (pending) {
            try {
                if (window.localStorage) window.localStorage.removeItem(PENDING_KEY);
            } catch (err) { /* ignore */ }
            // Defer so the page/app is fully wired before typing starts. A
            // resume wins over a deep link: that boot was already started, and
            // a broken link is beside the point while the machine is busy with
            // what its operator asked for a moment ago.
            setTimeout(function () { launch(pending, true); }, 0);
        } else if (linked) {
            // The visitor asked for this OS explicitly, so the wizard stays
            // shut and the scenario runs on its own.
            setTimeout(function () { launch(linked, false); }, 0);
        } else if (requested !== null) {
            // Somebody asked for a scenario this build does not have: a stale
            // link from an article, a typo, a key that has been renamed — or a
            // link that arrived with no key at all ("?boot="). The request is
            // explicit, so silence would read as "the emulator ignored me": the
            // dialog names the key, explains that nothing was booted and offers
            // the quick-boot list, and the parameter is left in the URL so the
            // visitor can see what was actually asked for. The test is against
            // null, not against truthiness — an empty key is a request too.
            setTimeout(function () { showNoScenario(requested); }, 0);
        }

        // Any operator keystroke ends the autoload warning — from there the
        // user types on their own ("don't touch the keyboard" no longer
        // applies). Idempotent: hides nothing when no balloon is shown.
        document.addEventListener("keydown", function () {
            hideBalloon();
        });
    }

    // Capture console output for prompt-waiting steps (called by iopage.js).
    // In-page feature: install through the internal bridge; falls back to
    // the legacy window.__consoleOutputHook surface when no bridge exists.
    var bridge = window.__yapdpBridge;
    if (bridge && bridge.setOutputHook) {
        bridge.setOutputHook(pushOutput);
    } else {
        window.__consoleOutputHook = pushOutput;
    }

    // Publish the autoload abort hook. imgerror.js is loaded BEFORE this module
    // (see pdp11.html) and calls it at runtime when an image fetch fails, so no
    // load-order coupling is needed.
    window.__autoloadAbort = abortAutoload;

    if (typeof document !== "undefined" && document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init);
    } else {
        init();
    }

    // Start fetching the build manifest right away so the wizard's list is
    // usually already filtered by the time the operator opens it.
    manifestPromise = fetchManifest();

    return {
        consolePageFor: consolePageFor,
        stepDelayMs: stepDelayMs,
        stepBytes: stepBytes,
        deviceFromSearch: deviceFromSearch,
        bootKeyFromSearch: bootKeyFromSearch,
        boundKey: boundKey,
        bufferContains: bufferContains,
        profileOf: profileOf,
        mergeHardware: mergeHardware,
        hardwareDirty: hardwareDirty,
        liveProfile: liveProfile,
        requirementText: requirementText,
        show: show,
        hide: hide,
        launch: launch,
        abortAutoload: abortAutoload,
        // Resolves to the build-manifest image list (or null when absent);
        // shared with the Info page so both surfaces agree on availability.
        manifest: function () { return manifestPromise; },
        // Re-render the wizard list now. Called by tauri-bundled.js once the
        // desktop bundle finishes mounting images, so a dialog opened during
        // the (async) mount window settles on the mounted set instead of the
        // unfiltered fallback. No-op while the dialog is closed — the next
        // show() re-renders anyway.
        refresh: function () {
            if (overlay && overlay.classList.contains("visible")) updateList();
        }
    };
})();
