/**
 * yaPDP — Quick boot wizard (magic wand)
 *
 * A small button pinned to the top-right corner of the Panel page opens a
 * modal dialog (shared modal-* style) listing every guest OS scenario from
 * osboot.js. Picking one boots the machine into that OS with a single click —
 * and, where credentials are known, types the login for you.
 *
 * Flow:
 *   1. If the OS needs a different machine profile (teletype vs VT52 console,
 *      LP11 printer present), the wizard persists the pending boot, applies
 *      the profile via Config.set() and reloads — devices are registered at
 *      load time, so a layout change needs a reload (same as CONFIG Apply).
 *      After the reload the wizard resumes the boot automatically.
 *   2. Switch to the operator console page (teletype or VT52 console).
 *   3. Reboot the machine (boot()) so the loader prints the @ prompt.
 *   4. Type `boot <dev>`, then each follow-up step (kernel name, Ctrl-D,
 *      login/password) with a delay that respects the configured teletype
 *      speed.
 *
 * Prompt-aware steps: a step with `waitFor` (e.g. "login:") is not sent on a
 * timer — the wizard watches the console output and types only once the
 * prompt appears (with a generous timeout fallback), so slow boots with lots
 * of output (2.11 BSD) still reach the login. The console output is captured
 * through window.__consoleOutputHook, which iopage.js feeds for every console
 * character (both teletype and VT52 console).
 *
 * Console input goes through the same global queue the physical keyboard
 * uses (window.dlReceiveQueue(0, bytes)), so it works for both the Model 33
 * ASR teletype and the VT52 console. Enter = 13, Ctrl-D = 4.
 *
 * Must be loaded AFTER osboot.js, config.js, pdp11-panel.js (switchPage) and
 * bootcode.js (boot); BEFORE pdp11-app.js.
 */
"use strict";

var QuickBoot = (function () {
    var overlay = null;

    // Pending boot device persisted across a config-driven reload.
    var PENDING_KEY = "yapdp.quickboot.pending";

    // Build manifest (media/manifest.json, generated by
    // tools/gen-media-manifest.js): logical urls of the images this
    // deployment ships. null while unknown or absent — the wizard then
    // offers every scenario (previous behaviour), so ad-hoc hosts and
    // file:// deployments keep working unchanged.
    var manifestList = null;
    var manifestPromise = null;

    // Fetch the build manifest once. Resolves to the image-url list, or null
    // when the deployment has no manifest (or fetch is unavailable). The
    // promise is shared so the wizard and the Info page see the same answer.
    function fetchManifest() {
        if (typeof fetch !== "function" || typeof document === "undefined") {
            return Promise.resolve(null);
        }
        return fetch("media/manifest.json", { cache: "no-store" })
            .then(function (r) { return r.ok ? r.json() : null; })
            .then(function (m) {
                manifestList = (m && Array.isArray(m.media)) ? m.media : null;
                return manifestList;
            })
            .catch(function () { manifestList = null; return null; })
            .then(function () {
                // The dialog may already be open when the manifest arrives
                // (slow host); re-render so the list settles on the truth.
                if (overlay && overlay.classList.contains("visible")) updateList();
                return manifestList;
            });
    }

    // ------------------------------------------------------------------
    // Pure helpers (no DOM) — unit-testable in Node
    // ------------------------------------------------------------------

    // Which console page hosts the operator console for the given config.
    function consolePageFor(cfg) {
        var t = cfg && cfg.consoleType;
        // Both graphical terminals share the vt52-console page; the teletype has
        // its own.
        return (t === "vt52" || t === "vt100") ? "vt52-console" : "teletype";
    }

    // Delay between typed steps; the authentic 110-baud teletype is slow, so
    // it gets more time for the guest to reach the next prompt.
    function stepDelayMs(speed) {
        return (speed === "authentic") ? 1600 : 800;
    }

    // True when the accumulated console output contains needle.
    function bufferContains(buffer, needle) {
        return !!needle && buffer.indexOf(needle) !== -1;
    }

    // The hardware profile a scenario requires; every scenario declares it
    // explicitly, with null meaning "keep the user's current setting".
    function profileOf(scenario) {
        return (scenario && scenario.hardware) || {};
    }

    // Merge a scenario's hardware profile over the current config. Keys set
    // to null in the profile are left untouched. Pure — unit-testable.
    function mergeHardware(cfg, profile) {
        var out = {};
        Object.keys(cfg || {}).forEach(function (k) { out[k] = cfg[k]; });
        if (profile.console) out.consoleType = profile.console;
        if (typeof profile.printer === "boolean") out.printer = profile.printer;
        if (typeof profile.vt11 === "boolean") out.vt11 = profile.vt11;
        if (typeof profile.forceUpperCaseOut === "boolean") {
            out.forceUpperCaseOut = profile.forceUpperCaseOut;
        }
        return out;
    }

    // True when the current config differs from the profile's requirements.
    // Only LAYOUT keys count: they are registered at load time, so a change
    // needs a page reload. forceUpperCaseOut is a live option (the console
    // printer reads it per printed character), so it must NOT force a reload —
    // see liveProfile()/launch().
    function hardwareDirty(cfg, profile) {
        if (!profile) return false;
        if (profile.console && cfg.consoleType !== profile.console) return true;
        if (typeof profile.printer === "boolean" &&
            cfg.printer !== profile.printer) return true;
        if (typeof profile.vt11 === "boolean" &&
            cfg.vt11 !== profile.vt11) return true;
        return false;
    }

    // Persist the profile's LIVE options (those that need no reload) and
    // report whether any of them actually changed. Pure — unit-testable.
    function liveProfile(cfg, profile) {
        var next = mergeHardware(cfg, profile);
        var changed = !!cfg && next.forceUpperCaseOut !== cfg.forceUpperCaseOut;
        return { changed: changed, forceUpperCaseOut: next.forceUpperCaseOut };
    }

    // Human-readable summary of the hardware the machine will actually boot
    // with for a scenario: the scenario's profile merged over the current
    // config (null profile keys keep the user's current setting). Always
    // states the console type and whether the LP11 printer is present.
    // Pure — unit-testable in Node.
    function requirementText(profile, cfg) {
        var merged = mergeHardware(cfg, profile);
        var parts = [];
        if (merged.consoleType === "vt100") parts.push("VT100 console");
        else if (merged.consoleType === "vt52") parts.push("VT52 console");
        else parts.push("teletype console");
        parts.push(merged.printer ? "LP11 printer" : "no printer");
        // Only positive requirements are shown — "no VT11" would be printed
        // for nearly every OS and just add noise (VT11 is off by default).
        if (merged.vt11 === true) parts.push("VT11 display");
        return parts.join(" · ");
    }

    // The raw key carried by a deep link from the landing OS galleries:
    // ?boot=<device>, or null only when the parameter is absent altogether.
    //
    // An EMPTY value is NOT "nobody asked": "?boot=" with nothing after it (or
    // a bare "?boot") is a link that lost its key — a broken template on the
    // page that emitted it — and the visitor gets the same explanation as for a
    // key that names no scenario. That is why this returns "" rather than null
    // for those, and why the caller tests for null rather than for truthiness.
    //
    // Kept apart from deviceFromSearch() so the page can tell "nobody asked for
    // anything" (say nothing) from "somebody asked for something we cannot do"
    // (say so). A dangling %-escape comes back as typed: it is about to be
    // shown to the person who typed it, not evaluated.
    // Pure — unit-testable in Node.
    function bootKeyFromSearch(search) {
        var s = search || "";
        var valued = /[?&]boot=([^&]*)/.exec(s);
        if (valued) {
            try {
                return decodeURIComponent(valued[1]);
            } catch (err) {
                return valued[1];
            }
        }
        // A bare "?boot" (no "=" at all) is the same broken link.
        return /[?&]boot(?:&|$)/.test(s) ? "" : null;
    }

    // The device key carried by that deep link. The key names a QuickBoot
    // SCENARIO, not a disk URL, so launch() applies the whole thing — the boot
    // command, the typed steps, the paper tape and the scenario's hardware
    // profile (console, printer, VT11, force-upper). An unknown or malformed
    // key returns null: the page opens, nothing throws, and nothing boots that
    // nobody asked for. The wizard explains the miss instead — see init().
    // Pure — unit-testable in Node.
    function deviceFromSearch(search) {
        var device = bootKeyFromSearch(search);
        if (device === null) return null;
        return (typeof OSBoot !== "undefined" && OSBoot.scenarioFor(device))
            ? device : null;
    }

    // Is a scenario bootable in THIS build? It is, when its image is in the
    // build manifest (browser deployments) or mounted in DataLoader (desktop
    // bundle, drag-and-drop imports) — the same union rule the wizard's list
    // uses (OSBoot.filterAvailable). A manifest that never resolved (ad-hoc
    // host, file://, fetch unavailable) proves nothing, so the scenario stays
    // "possibly bootable": the server may still have the image, and the boot
    // is allowed to try — an image that really is missing then falls through
    // to imgerror, exactly as before this check existed.
    // Pure — unit-testable in Node.
    function scenarioAvailable(scenario, manifest, mounted) {
        if (!scenario) return false;
        if (!Array.isArray(manifest)) return true;
        return OSBoot.filterAvailable(manifest, mounted || [])
            .indexOf(scenario) !== -1;
    }

    // The state URL carried by a deep link: ?state=<url>. This is the second
    // kind of shareable link (see docs/ROADMAP.md): ?boot= names a scenario
    // this build ships, while ?state= points at a machine state — a file the
    // project hosts, or one a visitor put on their own host. The two are
    // deliberately different: a boot key is an identifier into our allowlist,
    // a state URL is necessarily a pointer to foreign content, so it is
    // VALIDATED rather than trusted (scheme, length) and the loading path
    // defends itself (size bound, version, image fingerprints).
    //
    // Returns the url, or null when the parameter is absent.
    // Pure — unit-testable in Node.
    function stateUrlFromSearch(search) {
        var s = search || "";
        var m = /[?&]state=([^&]*)/.exec(s);
        if (!m) return null;
        var raw;
        try {
            raw = decodeURIComponent(m[1]);
        } catch (err) {
            raw = m[1];
        }
        return raw;
    }

    // Is a state URL one we will even attempt to fetch? A deep link is given
    // to us by whoever wrote the link, so this is the first gate: no scheme
    // we do not understand (javascript:, data: are traps, not states), and a
    // sane length. A relative path is resolved against the page, which is how
    // the project hosts its own states (states/<name>.state.zst).
    // Pure — unit-testable in Node.
    function stateUrlAllowed(url) {
        if (typeof url !== "string" || url.length === 0) return false;
        if (url.length > 512) return false;                      // a URL, not a payload
        if (/^[a-z][a-z0-9+.-]*:/i.test(url)) {                  // has a scheme
            // http(s) only. Everything else (javascript:, data:, blob:,
            // file:) is refused before a fetch is ever attempted.
            return /^https?:\/\//i.test(url);
        }
        // No scheme: a same-origin relative path. Refuse protocol-relative
        // (//host/...) too — that is a foreign host in disguise.
        return !/^\/\//.test(url);
    }

    // A key shown back to the visitor. A URL is not a place to trust, so the
    // text is tamed before it reaches the dialog:
    //   - control characters, line separators and bidi overrides become "?": a
    //     key of newlines would render as a multi-line paragraph, and U+202E
    //     would silently reorder what the visitor reads;
    //   - the cut is by CODE POINTS, not UTF-16 units, so a key ending in an
    //     emoji is not sliced through a surrogate pair and left as half a
    //     character.
    // Plain text only — the dialog is built with createElement/textContent, so
    // nothing here has to be escaped.
    function boundKey(key) {
        var s = String(key)
            .replace(/[\u0000-\u001F\u007F-\u009F\u2028\u2029\u202A-\u202E\u2066-\u2069]/g, "?");
        var points = Array.from(s);
        return points.length > 40 ? points.slice(0, 40).join("") + "…" : s;
    }

    // ------------------------------------------------------------------
    // Overlay DOM (browser only — not exercised by the Node tests)
    // ------------------------------------------------------------------

    function hide() {
        if (overlay) overlay.classList.remove("visible");
    }

    // --- Operator input gate --------------------------------------------
    // While the autoload toast below is up the wizard owns the machine, so
    // the operator's own input must NOT reach it. Every keyboard and pointer
    // event is intercepted in the CAPTURE phase on the document — before the
    // console keyboard (pdp11-app.js), the mobile key strips and the front
    // panel handlers ever see it — and dropped. The wizard's own bytes do not
    // travel through the DOM (they go straight to the DL11 bridge in
    // sendBytes()), so the boot sequence is unaffected. The toast's own
    // "Take control!" button is the single exemption: without it the gate
    // would be a trap.
    var GATED_EVENTS = [
        "keydown", "keypress", "keyup",
        "mousedown", "mouseup", "click",
        "pointerdown", "pointerup", "contextmenu"
    ];
    var gateOn = false;

    function gateEvent(e) {
        // The toasts are the ONLY way out of the autoload: let clicks on
        // either balloon (autoload or preparing) through.  The screenshot
        // button is also exempt — it is a permanent UI control, not console
        // input, and its right-click context menu must work during a boot.
        if (e.target && e.target.closest &&
            (e.target.closest("#quick-boot-balloon") ||
             e.target.closest("#quick-boot-preparing") ||
             e.target.closest("#screenshot-btn"))) return;
        // F11 toggles fullscreen (fullscreen.js) — an app control, not
        // console input; blocking it would strand the operator in a mode
        // they cannot leave while the boot runs.
        if (e.type === "keydown" && e.key === "F11") return;
        if (typeof e.preventDefault === "function") e.preventDefault();
        if (typeof e.stopImmediatePropagation === "function") {
            e.stopImmediatePropagation();
        } else if (typeof e.stopPropagation === "function") {
            e.stopPropagation();
        }
    }

    function setInputGate(on) {
        if (typeof document === "undefined") return;
        if (on === gateOn) return;
        gateOn = on;
        for (var i = 0; i < GATED_EVENTS.length; i++) {
            if (on) document.addEventListener(GATED_EVENTS[i], gateEvent, true);
            else document.removeEventListener(GATED_EVENTS[i], gateEvent, true);
        }
        if (document.body) {
            document.body.classList.toggle("quickboot-autoloading", on);
        }
    }

    // --- "Autoloading in progress" toast --------------------------------
    // A small toast shown while the wizard types the boot sequence. It now
    // carries the way OUT of the automatic boot: a "Take control!" button
    // that calls abortAutoload(), plus a spinner so a thick image crawling
    // over the network never reads as a hung machine. It disappears when the
    // sequence finishes or the operator takes control.
    var balloon = null;

    function ensureBalloon() {
        if (balloon) return balloon;
        balloon = document.createElement("div");
        balloon.id = "quick-boot-balloon";
        balloon.className = "quickboot-balloon";
        balloon.setAttribute("role", "status");
        balloon.setAttribute("aria-live", "polite");

        // Shared "work in progress" spinner, the same look as the startup
        // loading gate (see .yapdp-spin in css/pdp11.css).
        var spin = document.createElement("span");
        spin.className = "yapdp-spin quickboot-balloon-spin";
        spin.setAttribute("aria-hidden", "true");

        var text = document.createElement("span");
        text.className = "quickboot-balloon-text";
        text.textContent = "Autoloading in progress…";

        var take = document.createElement("button");
        take.type = "button";
        take.id = "quick-boot-take-control";
        take.className = "quickboot-take-control";
        take.textContent = "Take control!";
        take.addEventListener("click", function () { abortAutoload(); });

        balloon.appendChild(spin);
        balloon.appendChild(text);
        balloon.appendChild(take);
        document.body.appendChild(balloon);
        return balloon;
    }

    function showBalloon() {
        if (typeof document === "undefined") return;
        ensureBalloon().classList.add("visible");
        setInputGate(true);
    }

    function hideBalloon() {
        if (balloon) balloon.classList.remove("visible");
        setInputGate(false);
    }

    // --- "Preparing the machine" toast -----------------------------------
    // A shared state restores a RUNNING guest, but its disk image is still
    // fetched lazily on the first block read. Without a word the visitor sees
    // an idle screen, clicks, types, and only THEN watches a download strip
    // crawl by — three indicators saying three different things (measured
    // 2026-10-02). So when the image is not already in DataLoader, the wait is
    // stated up front: same toast look as the autoload, same input gate, but
    // NO "Take control!" — there is nothing to take over, the machine is
    // already the operator's, it is the DISK that is missing. While it loads,
    // input to the machine waits, exactly as it does during an autoload: the
    // guest is reading a block over the network and an operator keystroke
    // would race it in the same DL11 queue.
    var prepToast = null;

    // Resolve function for the OK-button wait on the preparing toast.
    // Set by showPreparing when steps are present; called by the OK button.
    var _stepsOkResolve = null;
    // Set by onRestored to indicate whether the state has steps to execute.
    // Used by applyStateLink to decide whether to close the balloon automatically.
    var _hasSteps = false;

    function ensurePrepToast() {
        if (prepToast) return prepToast;
        prepToast = document.createElement("div");
        prepToast.id = "quick-boot-preparing";
        prepToast.className = "quickboot-balloon";
        prepToast.setAttribute("role", "status");
        prepToast.setAttribute("aria-live", "polite");

        // Top row: spinner + label, always on the same line.
        var topRow = document.createElement("div");
        topRow.className = "quickboot-balloon-row";

        var spin = document.createElement("span");
        spin.className = "yapdp-spin quickboot-balloon-spin";
        spin.setAttribute("aria-hidden", "true");

        var text = document.createElement("span");
        text.className = "quickboot-balloon-text";
        text.id = "quick-boot-preparing-text";
        text.textContent = "Restoring the machine state\u2026";

        topRow.appendChild(spin);
        topRow.appendChild(text);

        var desc = document.createElement("span");
        desc.className = "quickboot-balloon-desc";
        desc.id = "quick-boot-preparing-desc";
        desc.style.display = "none";

        // Screenshot preview — shown when the manifest carries a screenshot.
        var screenshotImg = document.createElement("img");
        screenshotImg.className = "quickboot-balloon-screenshot";
        screenshotImg.id = "quick-boot-preparing-screenshot";
        screenshotImg.style.display = "none";

        // OK button — only shown when the state has steps to execute.
        // The operator must acknowledge before the autopilot types commands.
        var okBtn = document.createElement("button");
        okBtn.className = "quickboot-balloon-ok";
        okBtn.id = "quick-boot-preparing-ok";
        okBtn.textContent = "OK";
        okBtn.style.display = "none";
        okBtn.addEventListener("click", function () {
            okBtn.disabled = true;
            okBtn.textContent = "Running\u2026";
            if (_stepsOkResolve) _stepsOkResolve();
            // No actual steps to run — close the balloon now.
            // When there ARE steps, the step engine's onDone hides it.
            if (!_hasSteps) hidePreparing();
        });

        prepToast.appendChild(topRow);
        prepToast.appendChild(desc);
        prepToast.appendChild(screenshotImg);
        prepToast.appendChild(okBtn);
        document.body.appendChild(prepToast);
        return prepToast;
    }

    // Show the toast and follow the media-progress percentage while it runs.
    // The timer is the cheap way to keep the label live: the progress module
    // reports through the shared bar, and one label is all we need.
    // The toast says WHAT is happening; the media-progress strip at the
    // bottom says HOW FAR it is. Two places, two jobs — the percentage used to
    // appear in both at once, which read as a duplicate of the same sentence
    // rather than as two instruments (measured 2026-10-02).
    //
    // So this toast carries no number: it names the operation and stays until
    // the image lands. No polling timer is needed either — nothing here
    // changes while it is up.
    // `stepsMessage` is an optional human-readable description shown in the
    // balloon when a shareable state is being restored.
    // `buttonLabel` is an optional custom label for the OK button. When set,
    // the button is shown regardless of `hasSteps`; when absent, the button
    // is only shown when `hasSteps` is true (with a default "OK" label).
    // Show the preparing toast. When the button is visible, the returned
    // Promise resolves only when the operator clicks it (or immediately when
    // the button is hidden). The caller should await this Promise before
    // proceeding with step execution.
    function showPreparing(label, stepsMessage, hasSteps, buttonLabel) {
        if (typeof document === "undefined") return Promise.resolve();
        var el = ensurePrepToast();
        var text = el.querySelector("#quick-boot-preparing-text") || el.lastChild;
        text.textContent = label || "Restoring the machine state\u2026";
        var desc = el.querySelector("#quick-boot-preparing-desc");
        if (desc) {
            desc.textContent = stepsMessage || "";
            desc.style.display = stepsMessage ? "block" : "none";
        }
        var showOk = hasSteps || !!buttonLabel;
        var okBtn = el.querySelector("#quick-boot-preparing-ok");
        if (okBtn) {
            okBtn.disabled = false;
            okBtn.textContent = buttonLabel || "OK";
            okBtn.style.display = showOk ? "inline-block" : "none";
        }
        el.classList.add("visible");
        setInputGate(true);
        if (showOk) {
            return new Promise(function (resolve) {
                _stepsOkResolve = resolve;
            });
        }
        return Promise.resolve();
    }

    // Hide the toast and RELEASE the gate. Always called from a finally, so a
    // failed image load cannot leave the machine deaf — a stuck gate is the
    // trap we already built once and spent an evening undoing.
    function hidePreparing() {
        if (prepToast) prepToast.classList.remove("visible");
        setInputGate(false);
        _stepsOkResolve = null;
    }

    // Autoload abort token: bumped by every new launch() and by abortAutoload().
    // Timers capture the token they belong to and stop as soon as it no longer
    // matches, so a failed image load (imgerror.js) or a second launch can
    // neither leave the balloon up nor keep typing stale steps into a console
    // that is not responding.
    var autoloadToken = 0;

    function abortAutoload() {
        autoloadToken++;
        hideBalloon();
    }

    // Scenarios the wizard should offer right now. With no availability
    // information yet (no manifest, nothing mounted in DataLoader) the full
    // list is shown — the server may still have every image. Once the
    // manifest resolves (or images are mounted), only scenarios whose image
    // is in the manifest and/or mounted are listed (see OSBoot.filterAvailable).
    function currentScenarios() {
        var all = (typeof OSBoot !== "undefined" && OSBoot.BOOT_SCENARIOS)
            ? OSBoot.BOOT_SCENARIOS : [];
        if (typeof OSBoot === "undefined" ||
            typeof OSBoot.filterAvailable !== "function") return all;
        var mounted = (typeof DataLoader !== "undefined" &&
                       typeof DataLoader.list === "function")
            ? DataLoader.list() : [];
        if (!manifestList && (!mounted || mounted.length === 0)) return all;
        return OSBoot.filterAvailable(manifestList, mounted);
    }

    function updateList() {
        var listEl = overlay.querySelector(".quickboot-list");
        if (!listEl) return;
        listEl.innerHTML = "";
        var scenarios = currentScenarios();
        var cfg = (typeof Config !== "undefined" && Config.get)
            ? Config.get() : null;
        scenarios.forEach(function (s) {
            var btn = document.createElement("button");
            btn.type = "button";
            btn.className = "quickboot-option";
            btn.setAttribute("data-quickboot-device", s.device);
            var name = document.createElement("span");
            name.className = "quickboot-name";
            name.textContent = s.label;
            var cmd = document.createElement("span");
            cmd.className = "quickboot-cmd";
            cmd.textContent = s.boot + (s.autoLogin ? "  + auto-login" : "");
            btn.appendChild(name);
            btn.appendChild(cmd);
            var req = requirementText(profileOf(s), cfg);
            if (req) {
                var reqEl = document.createElement("span");
                reqEl.className = "quickboot-req";
                reqEl.textContent = req;
                btn.appendChild(reqEl);
            }
            btn.addEventListener("click", function () {
                launch(s.device);
            });
            listEl.appendChild(btn);
        });
    }

    // --- Operator overlay handover ---------------------------------------
    // A dialog that the SYSTEM raises on its own (a first-run hint, a refused
    // snapshot) may land while the autoload is typing. The autoload owns the
    // machine then, and its input gate swallows every click outside the toast —
    // so the dialog is visible but its buttons are dead, and the toast's own
    // way out sits underneath it. That is a trap with no exit but a reload.
    //
    // The rule: who raised the dialog decides. A dialog the OPERATOR opened
    // (reboot confirm, config-leave, snapshot manager) never races the autoload
    // because the gate blocks the click that would open it. A dialog the
    // SYSTEM raised is different — nobody asked and nobody can dismiss it — so
    // the autoload yields first and the operator gets the machine back.
    //
    // Call this BEFORE showing such a dialog. Returns true when the autoload
    // was stopped (the caller does not need the answer; it is for tests).
    function yieldToOperator() {
        if (!gateOn) return false;
        abortAutoload();
        return true;
    }

    // Did this launch arrive on a deep link (pdp11.html?boot=<device>)?
    // A visitor who followed a link to a specific guest OS has already chosen
    // what to do with the emulator; the first-run hint would explain a machine
    // they are already booting. Exposed so the hint can stand down instead of
    // duplicating the URL parsing in a second module.
    //
    // Reads location.search directly rather than the value init() captured:
    // init() may already have stripped the parameter (replaceState) and
    // resumed through the pending key.
    function arrivedByDeepLink() {
        if (typeof location === "undefined") return false;
        if (typeof bootKeyFromSearch === "function" &&
            bootKeyFromSearch(location.search) !== null) return true;
        // The parameter is gone (consumed), but the boot it started may be
        // deferred through a config reload: a pending key means this launch
        // IS that boot.
        try {
            if (window.localStorage &&
                window.localStorage.getItem(PENDING_KEY) !== null) return true;
        } catch (err) { /* ignore */ }
        return false;
    }

    // --- "Shared state" dialogs -------------------------------------------
    // The ?state= link has its own failure modes, and they are NOT the same as
    // "no such scenario": the URL was refused before we fetched anything (a
    // trap, not a state), or the fetch/parse/apply failed. Both reuse the
    // shared error shell and name the URL as TEXT — it came from a link nobody
    // validated.
    var STATE_REASON = {
        "missing-url": "the link carried no state URL",
        "not-a-state": "the file is not a machine state (it may be a disk image or a page)",
        "too-large": "the state is far larger than a state should be",
        "incompatible": "the state was taken on a different build of the disks it needs",
        "network": "the state could not be fetched",
        "local-file": "a page opened as a local file cannot fetch other files",
    };

    // A page opened as file:// cannot fetch ANYTHING — the browser blocks the
    // request before it leaves (origin null). imgerror already explains this
    // for images; a state link lands in the same wall, so it gets the same
    // explanation plus the way out that works offline: drag the file in.
    function isLocalFilePage() {
        return typeof window !== "undefined" && window.location &&
            window.location.protocol === "file:";
    }

    function showStateDialog(title, nodes) {
        if (typeof document === "undefined") return;
        if (!linkOverlay) {
            linkOverlay = document.createElement("div");
            linkOverlay.id = "quickboot-link-error";
            linkOverlay.className = "modal-overlay";
            linkOverlay.addEventListener("click", function (e) {
                if (e.target === linkOverlay) {
                    hideNoScenario();
                    return;
                }
                var action = e.target.getAttribute &&
                    e.target.getAttribute("data-bootlink-action");
                if (action === "wizard") {
                    hideNoScenario();
                    show();
                } else if (action === "close" ||
                        (e.target.closest && e.target.closest(".modal-close"))) {
                    hideNoScenario();
                }
            });
            document.body.appendChild(linkOverlay);
        }

        var box = document.createElement("div");
        box.className = "modal-box error";

        var titleEl = document.createElement("span");
        titleEl.className = "modal-title";
        titleEl.textContent = title;
        box.appendChild(titleEl);

        var intro = document.createElement("p");
        intro.className = "modal-intro";
        (nodes || []).forEach(function (n) {
            if (typeof n === "string") {
                intro.appendChild(document.createTextNode(n));
            } else if (n && n.code) {
                var code = document.createElement("code");
                code.textContent = boundKey(n.code);
                intro.appendChild(code);
            }
        });
        box.appendChild(intro);

        var gotIt = document.createElement("button");
        gotIt.type = "button";
        gotIt.className = "modal-close";
        gotIt.setAttribute("data-bootlink-action", "close");
        gotIt.textContent = "Got it";
        box.appendChild(gotIt);

        var wizardBtn = document.createElement("button");
        wizardBtn.type = "button";
        wizardBtn.className = "modal-close";
        wizardBtn.setAttribute("data-bootlink-action", "wizard");
        wizardBtn.textContent = "Choose a guest OS";
        box.appendChild(wizardBtn);

        linkOverlay.innerHTML = "";
        linkOverlay.appendChild(box);
        linkOverlay.classList.add("visible");
    }

    function showBadStateUrl(url) {
        showStateDialog("Shared state refused", [
            "The link asked for a machine state at ", { code: url },
            ", which this page will not fetch: only http(s) URLs and paths " +
            "relative to this site are accepted, so a link cannot make the " +
            "browser load something else entirely. Nothing was changed — pick " +
            "a guest OS from the quick-boot list, or ask for a corrected link."
        ]);
    }

    function showStateFailure(result) {
        var url = (result && result.url) || "";
        var why = STATE_REASON[result && result.reason];
        if (!why && result && /^http-/.test(result.reason || "")) {
            why = "the server answered " + result.reason.slice(5);
        }
        // A local-file page and a genuinely unreachable URL are different
        // problems with different fixes: name the one that actually happened,
        // and tell the visitor the way out that works without a server.
        if (isLocalFilePage()) {
            showStateDialog("Shared state not restored", [
                "This page was opened as a local file (file://), and a browser " +
                "does not let such a page fetch other files — so the state at ",
                { code: url },
                " could not be read. Open the emulator through a local web " +
                "server, or drop the .state file onto the Storage page, which " +
                "needs no network at all."
            ]);
            return;
        }
        showStateDialog("Shared state not restored", [
            "The machine state at ", { code: url },
            " was not restored: " + (why || "it could not be applied") +
            ". Nothing was booted and the machine is as it was — the link " +
            "may be stale, or the state may have been taken on a different " +
            "build of the emulator."
        ]);
    }

    // Fetch and apply a ?state= link, then report. The URL is dropped from the
    // address bar only on success: a link that could not be honoured keeps its
    // parameter so the visitor sees what was actually asked for.
    function applyStateLink(url) {
        if (typeof SnapshotStore === "undefined" ||
            typeof SnapshotStore.loadFromUrl !== "function") {
            showStateFailure({ url: url, reason: "not-a-state" });
            return;
        }
        // Raise the toast BEFORE the fetch so the browser has a frame to
        // render it before the state is applied. The manifest is not yet
        // known, so the generic label is used — onRestored will update it
        // with steps info once the container is unpacked. The gate goes up
        // with the toast and comes down in a finally: a failed load must not
        // leave the machine deaf, which is the trap this gate was built to
        // avoid in the first place.
        showPreparing("Restoring the machine state\u2026", null, false, null);
        SnapshotStore.loadFromUrl(url, {
            // Called after the container is unpacked and the machine restored,
            // before the guest is allowed to run on: the visitor is told the
            // disk is still coming, instead of meeting a download strip later.
            onRestored: function (manifest) {
                // Restore stepsMessage from sessionStorage if the manifest
                // doesn't carry it (e.g. after a config-driven reload that
                // persisted it in snapshots.js before calling location.reload).
                var stepsMessage = (manifest && manifest.stepsMessage) || null;
                if (!stepsMessage) {
                    try {
                        var saved = sessionStorage.getItem("yapdp.state-steps-message");
                        if (saved) { stepsMessage = saved; }
                    } catch (e) { /* ignore */ }
                }
                // Determine if there are steps to execute (from manifest or
                // sessionStorage fallback). When steps exist, the OK button
                // is shown and showPreparing waits for the operator to click it.
                var hasSteps = !!(manifest && manifest.steps &&
                    Array.isArray(manifest.steps) && manifest.steps.length > 0);
                if (!hasSteps) {
                    try {
                        var saved = sessionStorage.getItem("yapdp.state-steps");
                        if (saved) { hasSteps = true; }
                    } catch (e) { /* ignore */ }
                }
                _hasSteps = hasSteps;
                // Read the optional custom button label from the manifest.
                // When set, the OK button is shown with that label regardless
                // of steps; when absent, the button is only shown when there
                // are steps to execute (with a default "OK" label).
                // Fall back to sessionStorage for config-driven reloads.
                var buttonLabel = (manifest && manifest.buttonLabel) || null;
                if (!buttonLabel) {
                    try {
                        var saved = sessionStorage.getItem("yapdp.state-button-label");
                        if (saved) { buttonLabel = saved; }
                    } catch (e) { /* ignore */ }
                }
                // Show the preparing balloon for EVERY state restore, not just
                // when there are images to fetch or steps to run. The visitor
                // should always see that the machine is being restored.
                // When the button is visible, showPreparing returns a Promise
                // that resolves only after the operator clicks it.
                var prepPromise = showPreparing("Restoring the machine state\u2026", stepsMessage, hasSteps, buttonLabel);
                // The state is restored — stop the throbber. What remains is
                // waiting for the operator (OK button) or loading images, both
                // of which are idle from the machine's perspective.
                var spinEl = document.querySelector(".quickboot-balloon-spin");
                if (spinEl) spinEl.style.display = "none";
                // Show the screenshot preview if the manifest carries one.
                var screenshotUrl = (manifest && manifest.screenshot) || null;
                var screenshotImg = document.getElementById("quick-boot-preparing-screenshot");
                if (screenshotUrl && screenshotImg) {
                    screenshotImg.src = screenshotUrl;
                    screenshotImg.style.display = "block";
                }
                var urls = stateImageUrls(manifest);
                if (!urls.length) {
                    return prepPromise;
                }
                return prepPromise.then(function () {
                    // ASK FOR THE IMAGE — do not wait for the guest to. The disk is
                    // fetched lazily on the first block read, and that read comes
                    // from a guest sitting in WAIT for an operator keystroke. With
                    // the gate closed (we are waiting!) the operator cannot type,
                    // so the guest cannot read, so the image is never requested:
                    // the toast waited forever (found 2026-10-02). Asking ourselves
                    // breaks the circle — the fetch starts, the label tracks it,
                    // and the gate opens when it lands.
                    return Promise.all(urls.map(function (u) {
                        if (typeof window !== "undefined" &&
                            typeof window.__yapdpLoadImage === "function") {
                            return window.__yapdpLoadImage(u);
                        }
                        // No loader (legacy stack, or a harness): fall back to
                        // watching DataLoader so the gate still opens.
                        return waitForImages([u]);
                    }));
                });
            },
        }).then(function (result) {
            if (result && result.ok) {
                // State applied successfully. If there are no steps to
                // execute, close the balloon now. If there are steps, the
                // balloon stays up with the OK button — it will be closed
                // after the operator clicks OK and steps complete.
                if (!_hasSteps) hidePreparing();
                try {
                    history.replaceState(null, "",
                        location.pathname + location.hash);
                } catch (err) { /* ignore: the state is already applied */ }
                return;
            }
            hidePreparing();
            showStateFailure(result || { url: url });
        }, function () {
            hidePreparing();
            showStateFailure({ url: url, reason: "network" });
        });
    }

    // The image urls a state will read, from the manifest just unpacked: the
    // manifest names its device (states are per-scenario), and the scenario
    // table knows the image that device boots. No manifest, no guess — an
    // empty list simply means "no toast", never a wrong wait.
    function stateImageUrls(manifest) {
        var out = [];
        try {
            var s = manifest || null;
            if (s && s.device && typeof OSBoot !== "undefined") {
                var sc = (typeof OSBoot.scenarioFor === "function")
                    ? OSBoot.scenarioFor(s.device) : null;
                if (sc && sc.url) out.push(sc.url);
                else if (typeof OSBoot.urlFor === "function") out.push(OSBoot.urlFor(s.device));
            }
        } catch (err) { /* fall through with what we have */ }
        return out;
    }

    // Resolve when every listed image is in DataLoader, or when the wait has
    // run long enough that something else is wrong. Polling is cheap (a Map
    // lookup) and the alternative — hooking the loader — would couple this
    // code to a module that may change.
    function waitForImages(urls, timeoutMs) {
        if (!urls || !urls.length) return Promise.resolve();
        var deadline = Date.now() + (timeoutMs || 120000);
        return new Promise(function (resolve) {
            (function poll() {
                var all = urls.every(function (u) {
                    return typeof DataLoader !== "undefined" &&
                        typeof DataLoader.has === "function" && DataLoader.has(u);
                });
                if (all || Date.now() > deadline) return resolve();
                setTimeout(poll, 200);
            })();
        });
    }

    // --- "No such scenario" dialog ---------------------------------------
    // A deep link asking for a key this build does not have — a stale link from
    // an article, a typo, a renamed scenario — is an explicit request that
    // cannot be met. It gets the same treatment as a failed image fetch: the
    // .modal-box.error shell from css/pdp11.css, one "Got it" to dismiss and
    // one action that leads somewhere useful (the wizard's list). Built with
    // createElement/textContent, the way imgerror.js builds its overlay, so the
    // key — which comes from a URL nobody validated — is data, never markup.
    var linkOverlay = null;

    function hideNoScenario() {
        if (linkOverlay) linkOverlay.classList.remove("visible");
    }

    // `unavailable` picks the wording for a key that NAMES a scenario this
    // build simply does not ship the image for ("names no scenario in this
    // build" would be a lie — the scenario exists, its disk does not). The
    // dialog, the taming and the way out are otherwise identical, so the
    // visitor gets one explanation for both kinds of dead link.
    function showNoScenario(key, unavailable) {
        if (typeof document === "undefined") return;
        if (!linkOverlay) {
            linkOverlay = document.createElement("div");
            linkOverlay.id = "quickboot-link-error";
            linkOverlay.className = "modal-overlay";
            linkOverlay.addEventListener("click", function (e) {
                if (e.target === linkOverlay) {
                    hideNoScenario();
                    return;
                }
                var action = e.target.getAttribute &&
                    e.target.getAttribute("data-bootlink-action");
                if (action === "wizard") {
                    hideNoScenario();
                    show();
                } else if (action === "close" ||
                        (e.target.closest && e.target.closest(".modal-close"))) {
                    hideNoScenario();
                }
            });
            document.body.appendChild(linkOverlay);
        }

        var box = document.createElement("div");
        box.className = "modal-box error";

        var title = document.createElement("span");
        title.className = "modal-title";
        title.textContent = unavailable
            ? "Quick boot image not available"
            : "Quick boot scenario not found";
        box.appendChild(title);

        var intro = document.createElement("p");
        intro.className = "modal-intro";
        var tail = " — the machine is idle, exactly as if the page had been " +
            "opened without it. Pick a guest OS from the quick-boot list, or " +
            "type the boot command yourself at the @ prompt.";
        // An empty key is its own case: the link arrived without one, and
        // naming it would print an empty <code> element.
        if (key === "") {
            intro.appendChild(document.createTextNode(
                "The quick-boot link arrived with no key at all, so nothing " +
                "was booted" + tail));
        } else {
            intro.appendChild(document.createTextNode("The quick-boot key "));
            var code = document.createElement("code");
            code.textContent = boundKey(key);
            intro.appendChild(code);
            intro.appendChild(document.createTextNode(unavailable
                ? " names a scenario this build does not ship the image for, " +
                    "so nothing was booted" + tail
                : " names no scenario in this build, so nothing was booted" + tail));
        }
        box.appendChild(intro);

        // Dismiss first, then the "fix it" action — matching the other modals
        // (and imgerror's "Got it" → "Open Storage" order).
        var gotItBtn = document.createElement("button");
        gotItBtn.type = "button";
        gotItBtn.className = "modal-close";
        gotItBtn.setAttribute("data-bootlink-action", "close");
        gotItBtn.textContent = "Got it";
        box.appendChild(gotItBtn);

        var wizardBtn = document.createElement("button");
        wizardBtn.type = "button";
        wizardBtn.className = "modal-close";
        wizardBtn.setAttribute("data-bootlink-action", "wizard");
        wizardBtn.textContent = "Choose a guest OS";
        box.appendChild(wizardBtn);

        linkOverlay.innerHTML = "";
        linkOverlay.appendChild(box);
        linkOverlay.classList.add("visible");
    }

    function show() {
        if (!overlay) {
            overlay = document.createElement("div");
            overlay.id = "quick-boot-overlay";
            overlay.className = "modal-overlay";
            overlay.addEventListener("click", function (e) {
                if (e.target === overlay ||
                    (e.target.closest && e.target.closest(".quickboot-close"))) {
                    hide();
                }
            });
            document.body.appendChild(overlay);
        }
        overlay.innerHTML =
            '<div class="modal-box quickboot-box">' +
                '<span class="modal-title">Quick boot</span>' +
                '<p class="modal-intro">Pick a guest OS to boot it in one ' +
                    'click — credentials are typed automatically where known, ' +
                    'and the machine is reconfigured to suit the OS.</p>' +
                '<div class="quickboot-list"></div>' +
                '<button type="button" class="modal-close quickboot-close">Close</button>' +
            '</div>';
        updateList();
        overlay.classList.add("visible");
    }

    // --- Console output capture -----------------------------------------

    // Type the boot sequence for a scenario. `force` skips the hardware
    // profile check — used when resuming a pending boot after a reload.
    function launch(device, force) {
        var scenario = (typeof OSBoot !== "undefined" && OSBoot.scenarioFor)
            ? OSBoot.scenarioFor(device) : null;
        if (!scenario) return;

        var cfg = (typeof Config !== "undefined" && Config.get)
            ? Config.get() : null;
        var profile = profileOf(scenario);

        // Live option first: the force-upper flag needs no reload (the console
        // printer reads it per character), so it is applied straight away and
        // can never trigger the layout reload below on its own.
        var live = liveProfile(cfg, profile);
        if (live.changed && typeof Config.set === "function") {
            Config.set({ forceUpperCaseOut: live.forceUpperCaseOut });
        }

        // Apply the machine profile if the current config differs. Device
        // registration happens at load time, so a layout change reloads the
        // page (same as the CONFIG Apply button); the boot resumes afterwards.
        if (!force && cfg && hardwareDirty(cfg, profile)) {
            try {
                if (window.localStorage) window.localStorage.setItem(PENDING_KEY, device);
            } catch (err) { /* ignore */ }
            if (typeof Config.set === "function") {
                Config.set(mergeHardware(cfg, profile));
            }
            // This is an intentional reload: suppress the beforeunload warning
            // that would otherwise ask "Reload site?" (the CONFIG form is not
            // in sync with the freshly applied profile).
            window.__allowConfigReload = true;
            window.location.reload();
            return;
        }

        hide();

        // Select the paper tape (if any) and rewind it so the boot loader
        // reads it from the start.
        if (scenario.paperTape) {
            var ptrSelect = (typeof document !== "undefined")
                ? document.getElementById("ptr") : null;
            if (ptrSelect) ptrSelect.value = scenario.paperTape;
            if (typeof window.ptrRewindTape === "function") window.ptrRewindTape();
        }

        // Show the operator console — or the scenario's target page (e.g. the
        // VT11 Display page for Lunar Lander) — so the output is visible.
        if (typeof switchPage === "function") {
            switchPage(scenario.page || consolePageFor(cfg));
        }

        // Start "on a fresh page": clear teletype/LP11 paper and VT52 screens
        // before the reboot, so the boot banner lands on clean output.
        StepEngine.clearConsole();

        // ... and with a console able to SHOW that output at all: the teletype
        // on LINE, and no tape feeding bytes of its own while the steps are
        // typed. Both are the operator's controls, so the knob visibly turns.
        StepEngine.consoleWorkingState(
            { ttyMode: window.ttyMode, readerMode: window.ttyReaderMode },
            {
                setTtyMode: (typeof setTtyMode === "function") ? setTtyMode : null,
                setReaderMode: (typeof setReaderMode === "function") ? setReaderMode : null
            });

        // Reboot the machine so the boot loader reaches the @ prompt.
        if (typeof boot === "function") boot();

        // Forget any old console output so waitFor cannot match stale text.
        StepEngine.clearOutput();

        var base = stepDelayMs(cfg && cfg.teletypeSpeed);
        var steps = [{ send: scenario.boot }];
        var seq = scenario.steps || []; // paper tapes have no follow-up steps
        for (var i = 0; i < seq.length; i++) {
            steps.push(seq[i]);
        }
        // Own token for this run: a newer launch or an abort cancels it.
        var token = ++autoloadToken;
        showBalloon();
        StepEngine.runSteps(steps, {
            sendBytes: StepEngine.sendBytes,
            outputContains: StepEngine.outputContains,
            isCancelled: function () { return token !== autoloadToken; },
            onDone: function () { hideBalloon(); },
            stepDelayMs: base,
        });
    }

    // --- Wiring: the magic-wand button lives in pdp11.html on the Panel page
    function init() {
        if (typeof document === "undefined") return; // Node tests

        // Always wire the button — a deferred resume below must not leave it
        // dead, otherwise the wizard cannot be re-opened after a reload.
        // Wrapped, not passed directly: show() now takes the key of a scenario
        // nobody has, and a listener would hand it the click event instead.
        var btn = document.getElementById("quick-boot-btn");
        if (btn) btn.addEventListener("click", function () { show(); });

        // Resume a boot that was deferred by a config-driven reload.
        var pending = null;
        try {
            if (window.localStorage) pending = window.localStorage.getItem(PENDING_KEY);
        } catch (err) { /* ignore */ }

        // A deep link from the landing OS galleries. It is read once and
        // dropped from the URL right away: a hardware-profile change below
        // reloads the page, and the PENDING KEY — not the parameter — is what
        // brings the boot back. Leaving the parameter in place would start the
        // same scenario a second time after that reload.
        var search = (typeof location !== "undefined") ? location.search : "";
        var requested = bootKeyFromSearch(search);
        var linked = deviceFromSearch(search);
        // ?state=<url> — the other shareable link (see docs/ROADMAP.md):
        // somebody sent a machine state, not a scenario key. A state REPLACES
        // a boot (the guest was already running when it was taken), so it wins
        // over ?boot= when both are present — the more specific request.
        var stateUrl = stateUrlFromSearch(search);
        var stateLoad = stateUrl !== null && stateUrlAllowed(stateUrl);

        if (stateLoad) {
            // A ready machine WINS over an unfinished boot. A pending resume
            // exists to FINISH what was started; a state IS the finished
            // thing, and it is an explicit request from a link. So the state
            // goes first — and the pending key is dropped with it: the boot it
            // was holding is superseded, and leaving it behind would spring a
            // long-forgotten boot on the next plain launch.
            try {
                if (window.localStorage) window.localStorage.removeItem(PENDING_KEY);
            } catch (err) { /* ignore */ }
            // The parameter is dropped from the URL only once the state is
            // APPLIED — a link that could not be honoured keeps its parameter
            // (the visitor sees what was asked for).
            setTimeout(function () { applyStateLink(stateUrl); }, 0);
        } else if (pending) {
            try {
                if (window.localStorage) window.localStorage.removeItem(PENDING_KEY);
            } catch (err) { /* ignore */ }
            // Defer so the page/app is fully wired before typing starts.
            setTimeout(function () { launch(pending, true); }, 0);
        } else if (stateUrl !== null) {
            // A ?state= we refuse before fetching anything: a scheme that is
            // not http(s), a protocol-relative host, or a URL long enough to
            // be a payload. Say so instead of fetching a trap.
            setTimeout(function () { showBadStateUrl(stateUrl); }, 0);
        } else if (linked) {
            // The visitor asked for this OS explicitly, so the wizard stays
            // shut and the scenario runs on its own. The key names a real
            // scenario (deviceFromSearch said so); whether this BUILD ships its
            // image is a separate question, and the answer arrives with the
            // manifest — wait for it before booting. Booting a disk the build
            // does not have would stall the wizard on a mount that cannot
            // succeed (imgerror), long after the visitor has been told the
            // machine was theirs; the dialog is the honest answer.
            var mounted = (typeof DataLoader !== "undefined" &&
                           typeof DataLoader.list === "function")
                ? DataLoader.list() : [];
            var resolved = false;
            var resolveLink = function (manifest) {
                if (resolved) return;
                resolved = true;
                if (scenarioAvailable(OSBoot.scenarioFor(linked), manifest, mounted)) {
                    // The boot is really happening. A hardware-profile change
                    // inside launch() reloads the page, so the link must not
                    // outlive this load: drop it BEFORE the boot, or the reload
                    // starts the same scenario a second time. Dropped only here,
                    // on the path that boots: a link that cannot be honoured
                    // keeps its parameter, exactly like an unknown key — the
                    // visitor can see (and copy) what was actually asked for.
                    try {
                        history.replaceState(null, "",
                            location.pathname + location.hash);
                    } catch (err) { /* ignore: the boot still runs once */ }
                    launch(linked, false);
                } else {
                    showNoScenario(linked, true);
                }
            };
            // A manifest that never resolves proves nothing (ad-hoc host), so
            // the boot is allowed to proceed on its own after a short grace
            // period rather than hanging the page on a fetch that may never
            // finish. The grace is generous: on a cold cache the manifest is a
            // small JSON that lands well within it, and the boot itself takes
            // far longer than the wait.
            var graceMs = 4000;
            var graceTimer = setTimeout(function () { resolveLink(null); }, graceMs);
            if (manifestPromise && typeof manifestPromise.then === "function") {
                manifestPromise.then(function (manifest) {
                    clearTimeout(graceTimer);
                    resolveLink(manifest);
                });
            } else {
                resolveLink(null);
            }
        } else if (requested !== null) {
            // Somebody asked for a scenario this build does not have: a stale
            // link from an article, a typo, a key that has been renamed — or a
            // link that arrived with no key at all ("?boot="). The request is
            // explicit, so silence would read as "the emulator ignored me": the
            // dialog names the key, explains that nothing was booted and offers
            // the quick-boot list, and the parameter is left in the URL so the
            // visitor can see what was actually asked for. The test is against
            // null, not against truthiness — an empty key is a request too.
            setTimeout(function () { showNoScenario(requested); }, 0);
        }

        // The operator's own input no longer dismisses the toast: while the
        // autoload runs, the input gate set by showBalloon() swallows every
        // keyboard and pointer event (see gateEvent). The single way out is
        // the toast's "Take control!" button. Hiding the warning on a
        // keystroke used to let the operator type while the wizard kept
        // typing — the two byte streams then raced in the console.
    }

    // Publish the autoload abort hook. imgerror.js is loaded BEFORE this module
    // (see pdp11.html) and calls it at runtime when an image fetch fails, so no
    // load-order coupling is needed.
    window.__autoloadAbort = abortAutoload;
    window.__hideStatePreparing = hidePreparing;

    if (typeof document !== "undefined" && document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init);
    } else {
        init();
    }

    // Start fetching the build manifest right away so the wizard's list is
    // usually already filtered by the time the operator opens it.
    manifestPromise = fetchManifest();

    return {
        consolePageFor: consolePageFor,
        stepDelayMs: stepDelayMs,
        stepBytes: StepEngine.stepBytes,
        deviceFromSearch: deviceFromSearch,
        bootKeyFromSearch: bootKeyFromSearch,
        scenarioAvailable: scenarioAvailable,
        boundKey: boundKey,
        bufferContains: bufferContains,
        profileOf: profileOf,
        mergeHardware: mergeHardware,
        hardwareDirty: hardwareDirty,
        liveProfile: liveProfile,
        requirementText: requirementText,
        show: show,
        hide: hide,
        launch: launch,
        abortAutoload: abortAutoload,
        // The ?state= half of the deep-link contract (see docs/ROADMAP.md).
        stateUrlFromSearch: stateUrlFromSearch,
        stateUrlAllowed: stateUrlAllowed,
        // Stop the autoload so an operator-facing dialog the SYSTEM raised is
        // not shown into a machine that owns the input. See yieldToOperator().
        yieldToOperator: yieldToOperator,
        // "Preparing the machine" (a shared state whose disk is still being
        // fetched): the waiting toast and the input gate that goes with it.
        // Callers MUST drop it in a finally — a stuck gate leaves the machine
        // deaf, and that is the trap this gate was built to avoid.
        showPreparing: showPreparing,
        hidePreparing: hidePreparing,
        // Resume a ?state= link after the page reloaded for its device set
        // (Snapshots' init() calls this through window.__yapdpApplyStateLink).
        applyStateLinkNow: applyStateLink,
        // The hook Snapshots' init() calls after a reload-for-device-set.
        // Exposed under this name because init() cannot reach QuickBoot's
        // module scope directly (it only sees the global).
        __yapdpApplyStateLink: applyStateLink,
        // True when this launch came from pdp11.html?boot=<device> (or resumed
        // one through the pending key) — the first-run hint stands down then.
        arrivedByDeepLink: arrivedByDeepLink,
        // True while the autoload toast is up and the input gate is closed.
        isAutoloading: function () { return gateOn; },
        // Resolves to the build-manifest image list (or null when absent);
        // shared with the Info page so both surfaces agree on availability.
        manifest: function () { return manifestPromise; },
        // Re-render the wizard list now. Called by tauri-bundled.js once the
        // desktop bundle finishes mounting images, so a dialog opened during
        // the (async) mount window settles on the mounted set instead of the
        // unfiltered fallback. No-op while the dialog is closed — the next
        // show() re-renders anyway.
        refresh: function () {
            if (overlay && overlay.classList.contains("visible")) updateList();
        }
    };
})();
