name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # Run every night at 00:00 UTC
  workflow_dispatch:   # Allows running the cleanup manually via the button

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to delete logs and runs
    steps:
      - name: Delete runs older than 7 days
        uses: dmytro-diachenko/clean-workflow-action@v1.3.0
        with:
          runs_older_than: 7
          runs_to_keep: 3 # Just in case, keep the 3 most recent runs